import TripPageClient from "./TripPageClient"

// This would typically come from a database or API
const getAllTrips = () => [
  {
    id: 1,
    title: "Nandi Hills Sunrise Trek",
    description:
      "Witness the breathtaking sunrise from the historic Nandi Hills, perfect for photography enthusiasts and nature lovers.",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/d51e1dee7dc2446863cef50ccb257e31.jpg-4da0fZMjFFPKsgD62ie5kB5lLPKO4D.jpeg",
    price: "₹1,299",
    originalPrice: "₹1,599",
    duration: "1 Day",
    difficulty: "Easy",
    groupSize: "15-25",
    rating: 4.7,
    reviews: 89,
    slug: "nandi-hills-sunrise-trek",
    highlights: ["Sunrise viewpoint", "Historical fort", "Photography spots", "Bird watching"],
    location: "60km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Experience the magic of sunrise from one of Karnataka's most popular hill stations. Nandi Hills offers breathtaking panoramic views, ancient fort ruins, and excellent photography opportunities. This easy trek is perfect for beginners and families looking for a memorable day trip from Bangalore.",
    itinerary: [
      { time: "4:00 AM", activity: "Pickup from Bangalore" },
      { time: "5:30 AM", activity: "Reach Nandi Hills base" },
      { time: "6:00 AM", activity: "Trek to sunrise point" },
      { time: "6:30 AM", activity: "Sunrise viewing and photography" },
      { time: "8:00 AM", activity: "Explore historical fort" },
      { time: "9:30 AM", activity: "Breakfast at local restaurant" },
      { time: "11:00 AM", activity: "Return journey to Bangalore" },
      { time: "1:00 PM", activity: "Drop at pickup points" },
    ],
    inclusions: [
      "Transportation from Bangalore",
      "Professional guide",
      "Entry fees",
      "Breakfast",
      "Photography assistance",
      "First aid kit",
    ],
    exclusions: ["Personal expenses", "Additional meals", "Travel insurance", "Tips for guide"],
    whatToBring: [
      "Comfortable trekking shoes",
      "Water bottle",
      "Camera",
      "Light jacket",
      "Sunscreen",
      "Personal medication",
    ],
  },
  {
    id: 2,
    title: "Coorg Coffee Plantation Experience",
    description:
      "Immerse yourself in the misty hills of Coorg with coffee plantation tours, waterfalls, and authentic local culture.",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/84fc1cbf7bd4a97d9893abfdc41e0f9d%20%281%29.jpg-tniux34eccmxX3eI266tYCVwuB2QK3.jpeg",
    price: "₹2,999",
    originalPrice: "₹3,499",
    duration: "2 Days / 1 Night",
    difficulty: "Easy",
    groupSize: "15-20",
    rating: 4.8,
    reviews: 124,
    slug: "coorg-coffee-plantation-trek",
    highlights: ["Coffee plantation", "Abbey Falls", "Raja's Seat", "Local cuisine"],
    location: "250km from Bangalore",
    category: "Two Day Trip",
    fullDescription:
      "Discover the enchanting coffee country of Coorg with its rolling hills, aromatic plantations, and cascading waterfalls. This two-day experience combines nature, culture, and relaxation in one of South India's most beautiful hill stations.",
    itinerary: [
      { time: "Day 1 - 6:00 AM", activity: "Pickup from Bangalore" },
      { time: "10:00 AM", activity: "Reach Coorg, check-in to accommodation" },
      { time: "11:00 AM", activity: "Coffee plantation tour and tasting" },
      { time: "1:00 PM", activity: "Lunch at local restaurant" },
      { time: "3:00 PM", activity: "Visit Abbey Falls" },
      { time: "5:00 PM", activity: "Raja's Seat sunset viewpoint" },
      { time: "7:00 PM", activity: "Dinner and overnight stay" },
      { time: "Day 2 - 8:00 AM", activity: "Breakfast and check-out" },
      { time: "9:00 AM", activity: "Visit Dubare Elephant Camp" },
      { time: "12:00 PM", activity: "Lunch and departure to Bangalore" },
      { time: "6:00 PM", activity: "Reach Bangalore" },
    ],
    inclusions: [
      "Transportation from Bangalore",
      "Accommodation (1 night)",
      "All meals (1 breakfast, 2 lunches, 1 dinner)",
      "Coffee plantation tour",
      "Entry fees to all attractions",
      "Professional guide",
    ],
    exclusions: ["Personal expenses", "Additional activities", "Travel insurance", "Tips"],
    whatToBring: [
      "Comfortable clothing",
      "Trekking shoes",
      "Camera",
      "Personal medication",
      "Light jacket",
      "Sunscreen",
    ],
  },
  {
    id: 3,
    title: "Hampi Heritage Adventure",
    description:
      "Explore the ancient ruins of Hampi, a UNESCO World Heritage Site with rich history and stunning architecture.",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ed1ca01dfa2f309e07333fa3e42f1fc3.jpg-4vUtVyXbgPWXcqZYMDdNjOmOJag5jK.jpeg",
    price: "₹3,499",
    originalPrice: "₹3,999",
    duration: "2 Days / 1 Night",
    difficulty: "Moderate",
    groupSize: "12-15",
    rating: 4.9,
    reviews: 156,
    slug: "hampi-heritage-adventure",
    highlights: ["UNESCO site", "Virupaksha Temple", "Vittala Temple", "Coracle ride"],
    location: "350km from Bangalore",
    category: "Two Day Trip",
    fullDescription:
      "Step back in time and explore the magnificent ruins of Hampi, once the capital of the Vijayanagara Empire. This UNESCO World Heritage Site offers a perfect blend of history, architecture, and natural beauty.",
    itinerary: [
      { time: "Day 1 - 6:00 AM", activity: "Pickup from Bangalore" },
      { time: "11:00 AM", activity: "Reach Hampi, check-in" },
      { time: "12:00 PM", activity: "Lunch and rest" },
      { time: "2:00 PM", activity: "Visit Virupaksha Temple" },
      { time: "4:00 PM", activity: "Explore Hampi Bazaar" },
      { time: "6:00 PM", activity: "Sunset at Hemakuta Hill" },
      { time: "8:00 PM", activity: "Dinner and overnight stay" },
      { time: "Day 2 - 7:00 AM", activity: "Breakfast" },
      { time: "8:00 AM", activity: "Visit Vittala Temple complex" },
      { time: "10:00 AM", activity: "Coracle ride on Tungabhadra River" },
      { time: "12:00 PM", activity: "Lunch and departure" },
      { time: "7:00 PM", activity: "Reach Bangalore" },
    ],
    inclusions: [
      "Transportation from Bangalore",
      "Accommodation (1 night)",
      "All meals",
      "Entry fees to monuments",
      "Coracle ride",
      "Professional guide",
    ],
    exclusions: ["Personal expenses", "Additional activities", "Travel insurance", "Tips"],
    whatToBring: [
      "Comfortable walking shoes",
      "Hat and sunglasses",
      "Camera",
      "Water bottle",
      "Sunscreen",
      "Personal medication",
    ],
  },
  {
    id: 4,
    title: "Chikmagalur Hill Station Retreat",
    description:
      "Relax in the coffee capital of India with scenic drives, trekking, and plantation visits in the Western Ghats.",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/e770a010b14b8e61b2ab9c1cfc9c9fb0.jpg-aZ2r0TEKDfqQ010qIdAuLHypP4oLeG.jpeg",
    price: "₹2,799",
    originalPrice: "₹3,299",
    duration: "2 Days / 1 Night",
    difficulty: "Easy",
    groupSize: "15-20",
    rating: 4.7,
    reviews: 98,
    slug: "chikmagalur-hill-station",
    highlights: ["Mullayanagiri peak", "Coffee museum", "Hebbe Falls", "Hill station"],
    location: "240km from Bangalore",
    category: "Two Day Trip",
    fullDescription:
      "Escape to the serene hills of Chikmagalur, known for its coffee plantations, misty mountains, and pleasant climate. Perfect for nature lovers and those seeking a peaceful retreat.",
    itinerary: [
      { time: "Day 1 - 6:00 AM", activity: "Pickup from Bangalore" },
      { time: "10:00 AM", activity: "Reach Chikmagalur, check-in" },
      { time: "11:00 AM", activity: "Visit Coffee Museum" },
      { time: "1:00 PM", activity: "Lunch at local restaurant" },
      { time: "3:00 PM", activity: "Coffee plantation walk" },
      { time: "6:00 PM", activity: "Sunset at viewpoint" },
      { time: "8:00 PM", activity: "Dinner and overnight stay" },
      { time: "Day 2 - 6:00 AM", activity: "Early breakfast" },
      { time: "7:00 AM", activity: "Trek to Mullayanagiri peak" },
      { time: "11:00 AM", activity: "Visit Hebbe Falls" },
      { time: "1:00 PM", activity: "Lunch and departure" },
      { time: "6:00 PM", activity: "Reach Bangalore" },
    ],
    inclusions: [
      "Transportation from Bangalore",
      "Accommodation (1 night)",
      "All meals",
      "Coffee plantation tour",
      "Entry fees",
      "Professional guide",
    ],
    exclusions: ["Personal expenses", "Additional activities", "Travel insurance", "Tips"],
    whatToBring: ["Trekking shoes", "Warm clothing", "Camera", "Water bottle", "Personal medication", "Rain jacket"],
  },
  {
    id: 5,
    title: "Gokarna Beach & Temple Tour",
    description:
      "Perfect blend of spirituality and beach relaxation at the pristine beaches of Gokarna with temple visits.",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/43def08def9d0d28c1dbc687fad3de76.jpg-VvsWESStwC7nIjCnZQPA55OSchv74g.jpeg",
    price: "₹3,199",
    originalPrice: "₹3,699",
    duration: "2 Days / 1 Night",
    difficulty: "Easy",
    groupSize: "15-18",
    rating: 4.6,
    reviews: 87,
    slug: "gokarna-beach-retreat",
    highlights: ["Om Beach", "Kudle Beach", "Temple visits", "Beach activities"],
    location: "480km from Bangalore",
    category: "Two Day Trip",
    fullDescription:
      "Experience the perfect combination of spiritual serenity and coastal beauty at Gokarna. This sacred town offers pristine beaches, ancient temples, and a peaceful atmosphere away from crowded tourist spots.",
    itinerary: [
      { time: "Day 1 - 6:00 AM", activity: "Pickup from Bangalore" },
      { time: "12:00 PM", activity: "Reach Gokarna, check-in" },
      { time: "1:00 PM", activity: "Lunch and rest" },
      { time: "3:00 PM", activity: "Visit Mahabaleshwar Temple" },
      { time: "5:00 PM", activity: "Explore Gokarna Beach" },
      { time: "7:00 PM", activity: "Sunset at Om Beach" },
      { time: "8:30 PM", activity: "Dinner and overnight stay" },
      { time: "Day 2 - 7:00 AM", activity: "Breakfast" },
      { time: "8:00 AM", activity: "Beach hopping - Kudle, Half Moon, Paradise" },
      { time: "12:00 PM", activity: "Beach activities and lunch" },
      { time: "3:00 PM", activity: "Departure to Bangalore" },
      { time: "10:00 PM", activity: "Reach Bangalore" },
    ],
    inclusions: [
      "Transportation from Bangalore",
      "Accommodation (1 night)",
      "All meals",
      "Temple visits",
      "Beach activities",
      "Professional guide",
    ],
    exclusions: ["Personal expenses", "Water sports", "Travel insurance", "Tips"],
    whatToBring: ["Beach wear", "Sunscreen", "Hat and sunglasses", "Camera", "Flip-flops", "Personal medication"],
  },
  {
    id: 6,
    title: "Ooty Queen of Hills Experience",
    description: "Escape to the cool climate of Ooty with toy train rides, botanical gardens, and lake activities.",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/fe5c2327c69e9f3462844b909820385d.jpg-EotWWJMAppLNv3UySI6TR1Nul0a8gY.jpeg",
    price: "₹3,299",
    originalPrice: "₹3,799",
    duration: "2 Days / 1 Night",
    difficulty: "Easy",
    groupSize: "20-25",
    rating: 4.5,
    reviews: 112,
    slug: "ooty-queen-of-hills",
    highlights: ["Toy train", "Botanical Gardens", "Ooty Lake", "Tea gardens"],
    location: "270km from Bangalore",
    category: "Two Day Trip",
    fullDescription:
      "Discover the charm of Ooty, the Queen of Hill Stations, with its colonial architecture, lush gardens, and pleasant climate. Perfect for families and couples seeking a romantic getaway.",
    itinerary: [
      { time: "Day 1 - 6:00 AM", activity: "Pickup from Bangalore" },
      { time: "11:00 AM", activity: "Reach Ooty, check-in" },
      { time: "12:00 PM", activity: "Lunch and rest" },
      { time: "2:00 PM", activity: "Visit Botanical Gardens" },
      { time: "4:00 PM", activity: "Ooty Lake boating" },
      { time: "6:00 PM", activity: "Local market shopping" },
      { time: "8:00 PM", activity: "Dinner and overnight stay" },
      { time: "Day 2 - 8:00 AM", activity: "Breakfast" },
      { time: "9:00 AM", activity: "Toy train ride (subject to availability)" },
      { time: "11:00 AM", activity: "Visit tea gardens and factory" },
      { time: "1:00 PM", activity: "Lunch and departure" },
      { time: "7:00 PM", activity: "Reach Bangalore" },
    ],
    inclusions: [
      "Transportation from Bangalore",
      "Accommodation (1 night)",
      "All meals",
      "Entry fees to attractions",
      "Toy train tickets (subject to availability)",
      "Professional guide",
    ],
    exclusions: ["Personal expenses", "Additional activities", "Travel insurance", "Tips"],
    whatToBring: ["Warm clothing", "Comfortable shoes", "Camera", "Personal medication", "Light jacket", "Umbrella"],
  },
  {
    id: 7,
    title: "Kabini Wildlife Safari",
    description:
      "Wildlife adventure at Kabini with jungle safaris, river cruise, and nature walks in pristine forests.",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/52ae0c3e34336027ca3488a7c0a36505.jpg-riwRFfE8rsw7MEHRJk0JsJ2jZz0hZL.jpeg",
    price: "₹3,799",
    originalPrice: "₹4,299",
    duration: "2 Days / 1 Night",
    difficulty: "Easy",
    groupSize: "12-15",
    rating: 4.8,
    reviews: 76,
    slug: "kabini-wildlife-safari",
    highlights: ["Jungle safari", "River cruise", "Wildlife", "Nature walks"],
    location: "200km from Bangalore",
    category: "Two Day Trip",
    fullDescription:
      "Experience the thrill of wildlife at Kabini, one of India's premier wildlife destinations. Home to elephants, tigers, leopards, and diverse bird species in their natural habitat.",
    itinerary: [
      { time: "Day 1 - 6:00 AM", activity: "Pickup from Bangalore" },
      { time: "10:00 AM", activity: "Reach Kabini, check-in to resort" },
      { time: "11:00 AM", activity: "Welcome drink and briefing" },
      { time: "12:00 PM", activity: "Lunch and rest" },
      { time: "3:30 PM", activity: "Afternoon jungle safari" },
      { time: "6:30 PM", activity: "Return to resort" },
      { time: "8:00 PM", activity: "Dinner and overnight stay" },
      { time: "Day 2 - 6:00 AM", activity: "Early morning safari" },
      { time: "9:00 AM", activity: "Breakfast" },
      { time: "10:00 AM", activity: "River cruise and bird watching" },
      { time: "12:00 PM", activity: "Lunch and departure" },
      { time: "5:00 PM", activity: "Reach Bangalore" },
    ],
    inclusions: [
      "Transportation from Bangalore",
      "Accommodation (1 night)",
      "All meals",
      "2 jungle safaris",
      "River cruise",
      "Entry fees",
      "Naturalist guide",
    ],
    exclusions: ["Personal expenses", "Additional safaris", "Travel insurance", "Tips"],
    whatToBring: [
      "Neutral colored clothing",
      "Binoculars",
      "Camera with zoom lens",
      "Hat and sunglasses",
      "Insect repellent",
      "Personal medication",
    ],
  },
]

export async function generateStaticParams() {
  const trips = getAllTrips()
  return trips.map((trip) => ({
    slug: trip.slug,
  }))
}

interface TripPageProps {
  params: {
    slug: string
  }
}

export default function TripPage({ params }: TripPageProps) {
  return <TripPageClient params={params} />
}
