import { Trip } from "./types";

export const trips: Trip[] = [
  {
    id: 1,
    title: "Nandi Hills Sunrise Trek",
    description:
      "Witness the breathtaking sunrise from the historic Nandi Hills, perfect for photography enthusiasts and nature lovers.",
    image:
      "/images/11.jpeg",
    price: "₹799",
    originalPrice: "₹999",
    duration: "1 Day",
    difficulty: "Easy",
    groupSize: "15-25",
    rating: 4.7,
    reviews: 89,
    slug: "nandi-hills-sunrise-trek",
    highlights: [
      "Ideal for all trekkers - Beginners to seasoned hikers",
      "Ancient hill fort trail with scenic viewpoints",
      "Budget-friendly adventure",
      "Mesmerizing sunrise views over the landscape"
    ],
    location: "60km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Wake up to an unforgettable adventure! The Nandi Hills Sunrise Trek is one of the most sought-after quick getaways from Bangalore – perfect for beginners, nature lovers, and anyone craving fresh mountain air and mesmerizing sunrise views. This iconic hill fort offers breathtaking panoramic vistas, ancient temples, and is accessible to trekkers of all experience levels.",    itinerary: [
      { time: "11:15 PM", activity: "Departure from Bengaluru" },
      { time: "02:00 AM", activity: "Reach Nandi base, rest or stargaze" },
      { time: "03:30 AM", activity: "Start trek after orientation" },
      { time: "05:30 AM", activity: "Reach summit & enjoy the sunrise" },
      { time: "07:00 AM", activity: "Begin descent" },
      { time: "09:00 AM", activity: "Reach base & start return journey" },
      { time: "09:30 AM", activity: "Visit Bhoga Nandishwara Temple & breakfast stop (self-funded)" },
      { time: "11:00 AM", activity: "Drop-off at your original pickup points in Bangalore" },
    ],    pickupPoints: [
      "11:15 PM - Gopalan Arcade, RR Nagar",
      "11:30 PM - Kathriguppe Circle, Kathriguppe",
      "11:45 PM - BMTC Bus Stop, Banashankari",
      "12:05 AM - Udupi Garden Signal, BTM Layout",
      "12:15 AM - Bus Stop, Silk Board",
      "12:45 AM - Shell Petrol Pump, Bellandur",
      "01:15 AM - Opp. Kalamandir, Marathahalli",
      "01:35 AM - HP Petrol Pump, Tin Factory",
      "01:45 AM - Opp. Esteem Mall, Hebbal",
    ],
    inclusions: [
      "Comfortable round-trip transportation from Bangalore",
      "Forest or trekking guide",
      "Trek lead from the Abhitrip Team",
      "Access to first-aid kit",
      "Forest permit if any (INCLUDED)",
    ],
    exclusions: [
      "Meals (breakfast/snacks)",
      "Bottled water or other personal purchases",
      "Insurance or items not listed under inclusions",
    ],
    whatToBring: [
      "A photocopy of your Aadhar/Voter ID (mandatory)",
      "Small backpack (to carry essentials)",
      "Water bottles – 1–2 liters",
      "Raincoat/poncho or bag cover (in case of rain)",
      "Trekking shoes with good grip + extra socks",
      "Torch/headlamp (required for night trek)",
      "Power bank",
      "Snacks (dry fruits, energy bars, etc.)",
      "Any personal medication",
    ],
  },
  {
    id: 2,
    title: "Skandagiri Sunrise Trek",
    description:
      "Experience the magic of trekking under the stars and watching the sunrise from above the clouds!",
    image:
      "/images/adventure-sports.jpeg",
    price: "₹1249",
    originalPrice: "₹1499",
    duration: "1 Day",
    difficulty: "Moderate",
    groupSize: "15-25",
    rating: 4.8,
    reviews: 75,
    slug: "skandagiri-sunrise-trek",
    highlights: [
      "Early morning trek to one of Karnataka's most scenic sunrise points",
      "Mesmerizing sunrise view above the clouds",
      "360° views from the summit, often above the clouds"
    ],
    location: "70km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Experience the magic of trekking under the stars and watching the sunrise from above the clouds! The Skandagiri Sunrise Trek offers an unforgettable night hike through ancient fort ruins, misty trails, and panoramic views of Nandi Hills and beyond. Just 70 km from Bangalore, this trek is perfect for both beginners and seasoned adventurers looking for a quick escape into nature.",    itinerary: [
      { time: "10:45 PM", activity: "Departure from Bengaluru" },
      { time: "03:00 AM", activity: "Arrive at the base; rest or enjoy a calm walk under the stars" },
      { time: "05:30 AM", activity: "Begin trek after a safety briefing from our guides" },
      { time: "07:15 AM", activity: "Reach the summit; enjoy sunrise and scenic cloud views" },
      { time: "08:00 AM", activity: "Start your descent" },
      { time: "10:00 AM", activity: "Reach base and board vehicle for return" },
      { time: "11:30 AM", activity: "Halt for self-funded breakfast & freshen-up" },
      { time: "01:00 PM", activity: "Arrive back in Bangalore; drop-off at your original pickup location" },
    ],
    pickupPoints: [
      "10:45 PM - Gopalan Arcade, RR Nagar",
      "11:15 PM - BMTC Bus Stop, Banashankari",
      "11:35 PM - Udupi Garden Signal, BTM Layout",
      "11:45 PM - Bus Stop, Silk Board",
      "12:15 AM - Shell Petrol Pump, Bellandur",
      "12:45 AM - Opp. Kalamandir, Marathahalli",
      "01:05 AM - HP Petrol Pump, Tin Factory",
      "01:15 AM - Opp. Esteem Mall, Hebbal",
    ],
    inclusions: [
      "Comfortable round-trip transportation from Bangalore",
      "Forest permit (INCLUDED)",
      "Trek lead from the Abhitrip Team",
      "Access to first-aid kit",
    ],
    exclusions: [
      "Meals (breakfast/snacks)",
      "Bottled water or other personal purchases",
      "Insurance or items not listed under inclusions",
    ],
    whatToBring: [
      "A photocopy of your Aadhar/Voter ID (mandatory)",
      "Small backpack (to carry essentials)",
      "Water bottles – 1–2 liters",
      "Raincoat/poncho or bag cover (in case of rain)",
      "Trekking shoes with good grip + extra socks",
      "Torch/headlamp (required for night trek)",
      "Power bank",
      "Snacks (dry fruits, energy bars, etc.)",
      "Any personal medication",
    ],
  },
  {
    id: 3,
    title: "Kunti Betta Sunrise Trek",
    description:
      "Trek the twin hills associated with Mahabharata and witness a stunning sunrise over Pandavapura lake.",
    image:
      "/images/adventure-sports.jpeg",
    price: "₹799",
    originalPrice: "₹999",
    duration: "1 Day",
    difficulty: "Easy",
    groupSize: "15-20",
    rating: 4.4,
    reviews: 56,
    slug: "kunti-betta-sunrise-trek",
    highlights: [
      "Night trek with flashlight-lit trails under the stars",
      "Sunrise view from the summit with 360° panoramic beauty",
      "Budget-friendly adventure",
      "Historical significance linked to Mahabharata"
    ],
    location: "125km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Looking for a thrilling night trek with breathtaking sunrise views? The Kunti Betta Sunrise Trek is the perfect blend of adventure, nature, and mythology just 125 km from Bangalore in the historic town of Pandavapura, near Mysore.",    itinerary: [
      { time: "11:15 PM", activity: "Departure from Bengaluru" },
      { time: "03:30 AM", activity: "Arrive at Kunti Betta base" },
      { time: "03:45 AM", activity: "Briefing by the trek guide" },
      { time: "04:00 AM", activity: "Begin the night trek" },
      { time: "05:00 AM", activity: "Reach the summit & enjoy the sunrise" },
      { time: "06:30 AM", activity: "Start descent" },
      { time: "09:30 AM", activity: "Breakfast stop (self-funded)" },
      { time: "11:00 AM", activity: "Depart for Bangalore" },
      { time: "01:00 PM", activity: "Drop-off at original pickup points" },
    ],
    pickupPoints: [
      "11:15 PM - Benniganahalli Metro Station, Tin Factory",
      "11:35 PM - Kalamandir, Marathahalli",
      "11:50 PM - Akme Harmony, Bellandur",
      "12:05 AM - Silkboard Bus Stop",
      "12:15 AM - Udupi Garden Signal, BTM",
      "12:30 AM - Banashankari Bus Stop",
      "12:45 AM - Kathriguppe Circle",
      "01:00 AM - Gopalan Arcade Mall, RR Nagar",
      "01:15 AM - Kengeri Bus Stop",
    ],
    inclusions: [
      "Comfortable round-trip transportation from Bangalore",
      "Forest or trekking guide",
      "Trek lead from the Abhitrip Team",
      "Access to first-aid kit",
      "Forest permit if any (INCLUDED)",
    ],
    exclusions: [
      "Meals (breakfast/snacks)",
      "Bottled water or other personal purchases",
      "Insurance or items not listed under inclusions",
    ],
    whatToBring: [
      "A photocopy of your Aadhar/Voter ID (mandatory)",
      "Small backpack (to carry essentials)",
      "Water bottles – 1–2 liters",
      "Raincoat/poncho or bag cover (in case of rain)",
      "Trekking shoes with good grip + extra socks",
      "Torch/headlamp (required for night trek)",
      "Power bank",
      "Snacks (dry fruits, energy bars, etc.)",
      "Any personal medication",
    ],
  },
  {
    id: 4,
    title: "Shivagange Sunrise Trek",
    description:
      "Discover the mystical Shivagange hills with ancient temples and breathtaking sunrise views.",
    image:
      "/images/adventure-sports.jpeg",
    price: "₹899",
    originalPrice: "₹1199",
    duration: "1 Day",
    difficulty: "Moderate",
    groupSize: "15-20",
    rating: 4.5,
    reviews: 67,
    slug: "shivagange-sunrise-trek",
    highlights: [
      "Ancient temples and spiritual significance",
      "Unique rock formations and caves",
      "Stunning sunrise views from the summit",
      "Mix of adventure and spirituality"
    ],
    location: "60km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Embark on a spiritual and adventurous journey to Shivagange, known for its unique rock formations, ancient temples, and breathtaking sunrise views. This trek combines physical challenge with spiritual exploration, making it perfect for those seeking both adventure and inner peace.",    itinerary: [
      { time: "11:30 PM", activity: "Departure from Bengaluru" },
      { time: "03:30 AM", activity: "Reach Shivagange base, rest and prepare" },
      { time: "04:30 AM", activity: "Start trek after safety briefing" },
      { time: "06:00 AM", activity: "Reach summit & enjoy the sunrise" },
      { time: "07:30 AM", activity: "Explore temples and caves" },
      { time: "08:30 AM", activity: "Begin descent" },
      { time: "10:00 AM", activity: "Reach base & start return journey" },
      { time: "11:00 AM", activity: "Breakfast stop (self-funded)" },
      { time: "01:00 PM", activity: "Drop-off at your original pickup points in Bangalore" },
    ],
    pickupPoints: [
      "11:30 PM - Gopalan Arcade, RR Nagar",
      "11:45 PM - Kathriguppe Circle, Kathriguppe",
      "12:00 AM - BMTC Bus Stop, Banashankari",
      "12:20 AM - Udupi Garden Signal, BTM Layout",
      "12:30 AM - Bus Stop, Silk Board",
      "01:00 AM - Shell Petrol Pump, Bellandur",
      "01:30 AM - Opp. Kalamandir, Marathahalli",
      "01:50 AM - HP Petrol Pump, Tin Factory",
      "02:00 AM - Opp. Esteem Mall, Hebbal",
    ],
    inclusions: [
      "Comfortable round-trip transportation from Bangalore",
      "Expert trek guide",
      "Trek lead from the Abhitrip Team",
      "Access to first-aid kit",
      "Temple entry permissions",
    ],
    exclusions: [
      "Meals (breakfast/snacks)",
      "Bottled water or other personal purchases",
      "Insurance or items not listed under inclusions",
      "Temple donations (optional)",
    ],
    whatToBring: [
      "A photocopy of your Aadhar/Voter ID (mandatory)",
      "Small backpack (to carry essentials)",
      "Water bottles – 1–2 liters",
      "Raincoat/poncho or bag cover (in case of rain)",
      "Trekking shoes with good grip + extra socks",
      "Torch/headlamp (required for night trek)",
      "Power bank",
      "Snacks (dry fruits, energy bars, etc.)",
      "Any personal medication",
    ],
  },
  {
    id: 5,
    title: "Uttari Betta Sunrise Trek",
    description:
      "Experience the thrill of sunrise trekking at Uttari Betta with panoramic views of the Western Ghats.",
    image:
      "/images/adventure-sports.jpeg",
    price: "₹949",
    originalPrice: "₹1249",
    duration: "1 Day",
    difficulty: "Moderate",
    groupSize: "15-20",
    rating: 4.6,
    reviews: 82,
    slug: "uttari-betta-sunrise-trek",
    highlights: [
      "Spectacular sunrise views over the Western Ghats",
      "Challenging yet rewarding trek suitable for beginners",
      "Rich biodiversity and scenic landscapes",
      "Perfect for photography enthusiasts"
    ],
    location: "100km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Uttari Betta offers one of the most rewarding sunrise treks near Bangalore. Known for its scenic beauty and challenging terrain, this trek provides stunning views of the Western Ghats and is perfect for adventure enthusiasts looking for a moderate challenge.",    itinerary: [
      { time: "10:30 PM", activity: "Departure from Bengaluru" },
      { time: "03:00 AM", activity: "Reach Uttari Betta base" },
      { time: "03:30 AM", activity: "Safety briefing and trek preparation" },
      { time: "04:00 AM", activity: "Begin the trek" },
      { time: "05:45 AM", activity: "Reach summit & enjoy the sunrise" },
      { time: "07:00 AM", activity: "Photography and exploration time" },
      { time: "08:00 AM", activity: "Start descent" },
      { time: "09:30 AM", activity: "Reach base & start return journey" },
      { time: "10:30 AM", activity: "Breakfast stop (self-funded)" },
      { time: "12:30 PM", activity: "Drop-off at your original pickup points in Bangalore" },
    ],
    pickupPoints: [
      "10:30 PM - Gopalan Arcade, RR Nagar",
      "10:45 PM - Kathriguppe Circle, Kathriguppe",
      "11:00 PM - BMTC Bus Stop, Banashankari",
      "11:20 PM - Udupi Garden Signal, BTM Layout",
      "11:30 PM - Bus Stop, Silk Board",
      "12:00 AM - Shell Petrol Pump, Bellandur",
      "12:30 AM - Opp. Kalamandir, Marathahalli",
      "12:50 AM - HP Petrol Pump, Tin Factory",
      "01:00 AM - Opp. Esteem Mall, Hebbal",
    ],
    inclusions: [
      "Comfortable round-trip transportation from Bangalore",
      "Professional trek guide",
      "Trek lead from the Abhitrip Team",
      "Access to first-aid kit",
      "Forest permits (if required)",
    ],
    exclusions: [
      "Meals (breakfast/snacks)",
      "Bottled water or other personal purchases",
      "Insurance or items not listed under inclusions",
    ],
    whatToBring: [
      "A photocopy of your Aadhar/Voter ID (mandatory)",
      "Small backpack (to carry essentials)",
      "Water bottles – 1–2 liters",
      "Raincoat/poncho or bag cover (in case of rain)",
      "Trekking shoes with good grip + extra socks",
      "Torch/headlamp (required for night trek)",
      "Power bank",
      "Snacks (dry fruits, energy bars, etc.)",
      "Any personal medication",
    ],
  },
  {
    id: 6,
    title: "Adiyogi Gudibande Fort Trek",
    description:
      "Explore the historic Gudibande Fort and witness the majestic Adiyogi statue on this adventurous day trek.",
    image:
      "/images/adventure-sports.jpeg",
    price: "₹1099",
    originalPrice: "₹1399",
    duration: "1 Day",
    difficulty: "Moderate",
    groupSize: "15-25",
    rating: 4.7,
    reviews: 93,
    slug: "adiyogi-gudibande-fort-trek",
    highlights: [
      "Historic Gudibande Fort with ancient architecture",
      "Stunning views of the 112-ft Adiyogi statue",
      "Panoramic views of the surrounding landscape",
      "Perfect blend of history, spirituality, and adventure"
    ],
    location: "100km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Discover the perfect combination of history, spirituality, and adventure at Gudibande Fort. This trek offers stunning views of the iconic 112-ft Adiyogi statue and takes you through ancient fort ruins with rich historical significance.",    itinerary: [
      { time: "06:00 AM", activity: "Departure from Bengaluru" },
      { time: "10:00 AM", activity: "Reach Gudibande base & visit Adiyogi statue" },
      { time: "10:30 AM", activity: "Safety briefing and trek preparation" },
      { time: "11:00 AM", activity: "Begin trek to Gudibande Fort" },
      { time: "12:30 PM", activity: "Reach fort summit & explore" },
      { time: "01:30 PM", activity: "Lunch break (self-funded)" },
      { time: "02:30 PM", activity: "Photography and exploration time" },
      { time: "03:30 PM", activity: "Begin descent" },
      { time: "04:30 PM", activity: "Reach base & start return journey" },
      { time: "07:00 PM", activity: "Drop-off at your original pickup points in Bangalore" },
    ],
    pickupPoints: [
      "06:15 AM - Gopalan Arcade, RR Nagar",
      "06:30 AM - Kathriguppe Circle, Kathriguppe",
      "06:45 AM - BMTC Bus Stop, Banashankari",
      "07:05 AM - Udupi Garden Signal, BTM Layout",
      "07:15 AM - Bus Stop, Silk Board",
      "07:45 AM - Shell Petrol Pump, Bellandur",
      "08:15 AM - Opp. Kalamandir, Marathahalli",
      "08:35 AM - HP Petrol Pump, Tin Factory",
      "08:45 AM - Opp. Esteem Mall, Hebbal",
    ],
    inclusions: [
      "Comfortable round-trip transportation from Bangalore",
      "Professional trek guide",
      "Trek lead from the Abhitrip Team",
      "Access to first-aid kit",
      "Entry to Adiyogi statue area",
    ],
    exclusions: [
      "Meals (lunch/snacks)",
      "Bottled water or other personal purchases",
      "Insurance or items not listed under inclusions",
    ],
    whatToBring: [
      "A photocopy of your Aadhar/Voter ID (mandatory)",
      "Small backpack (to carry essentials)",
      "Water bottles – 1–2 liters",
      "Raincoat/poncho or bag cover (in case of rain)",
      "Trekking shoes with good grip + extra socks",
      "Hat or cap for sun protection",
      "Power bank",
      "Snacks (dry fruits, energy bars, etc.)",
      "Any personal medication",
    ],
  },
  {
    id: 7,
    title: "Coorg Trip – The Scotland of India",
    description:
      "Discover the lush beauty and cultural richness of Coorg – often hailed as the 'Scotland of India.' From majestic viewpoints and roaring waterfalls to spiritual sanctuaries and elephant encounters, this 2-day escape is crafted for nature lovers, photographers, and adventure seekers.",
    image:
      "/images/mountains/coorg.jpg",
    price: "₹3,999",
    originalPrice: "₹4,499",
    duration: "2 Days / 1 Night",
    difficulty: "Easy",
    groupSize: "15-20",
    rating: 4.8,
    reviews: 124,
    slug: "coorg-trip",
    highlights: [
      "Mandalpatti View Point - Panoramic vistas of Coorg's verdant landscapes",
      "Abbey Falls - A roaring cascade in the heart of nature",
      "Raja Seat - Sunset views that steal your breath",
      "Harangi Elephant Camp - Close encounter with gentle giants",
      "Namdroling Monastery - Golden Temple and Tibetan culture"
    ],
    location: "250km from Bangalore",
    category: "Two Day Trip",
    fullDescription:
      "Discover the lush beauty and cultural richness of Coorg – often hailed as the 'Scotland of India.' From majestic viewpoints and roaring waterfalls to spiritual sanctuaries and elephant encounters, this 2-day escape is crafted for nature lovers, photographers, and adventure seekers. Ideal for solo travelers, friends, and weekend wanderers.",    itinerary: [
      { time: "Day 1 - 06:30 AM", activity: "Departure from Bangalore" },
      { time: "11:00 AM", activity: "Arrive in Coorg & check-in" },
      { time: "12:00 PM", activity: "Lunch at local restaurant" },
      { time: "01:30 PM", activity: "Visit Abbey Falls" },
      { time: "03:00 PM", activity: "Explore local coffee plantations" },
      { time: "05:00 PM", activity: "Raja Seat for sunset views" },
      { time: "07:00 PM", activity: "Dinner & overnight stay" },
      { time: "Day 2 - 07:00 AM", activity: "Breakfast & check-out" },
      { time: "08:30 AM", activity: "Visit Namdroling Monastery" },
      { time: "10:00 AM", activity: "Harangi Elephant Camp experience" },
      { time: "12:00 PM", activity: "Mandalpatti View Point" },
      { time: "02:00 PM", activity: "Lunch & departure to Bangalore" },
      { time: "07:00 PM", activity: "Arrive in Bangalore" },
    ],
    pickupPoints: [
      "06:30 AM - Gopalan Arcade, RR Nagar",
      "06:45 AM - Kathriguppe Circle, Kathriguppe",
      "07:00 AM - BMTC Bus Stop, Banashankari",
      "07:20 AM - Udupi Garden Signal, BTM Layout",
      "07:30 AM - Bus Stop, Silk Board",
      "08:00 AM - Shell Petrol Pump, Bellandur",
      "08:30 AM - Opp. Kalamandir, Marathahalli",
      "08:50 AM - HP Petrol Pump, Tin Factory",
      "09:00 AM - Opp. Esteem Mall, Hebbal",
    ],
    inclusions: [
      "Comfortable round-trip transportation from Bangalore",
      "1 night accommodation in Coorg",
      "All meals (2 breakfast, 2 lunch, 1 dinner)",
      "Professional tour guide",
      "Entry fees to all attractions",
      "Elephant camp experience",
    ],
    exclusions: [
      "Personal expenses and shopping",
      "Adventure activities not mentioned",
      "Insurance or items not listed under inclusions",
      "Tips for guides and drivers",
    ],
    whatToBring: [
      "Valid ID proof (Aadhar/Voter ID/Passport)",
      "Comfortable walking shoes",
      "Light cotton clothes and warm jacket",
      "Camera for photography",
      "Personal medication",
      "Umbrella or raincoat",
      "Power bank and chargers",
    ],
  },
  {
    id: 8,
    title: "Gokarna Murudeshwar Trip",
    description:
      "Experience the perfect blend of pristine beaches, ancient temples, and coastal adventure in this unforgettable 2-day getaway to Gokarna and Murudeshwar.",
    image:
      "",
    price: "₹3,699",
    originalPrice: "₹4,799",
    duration: "2 Days / 1 Night",
    difficulty: "Easy",
    groupSize: "15-25",
    rating: 4.6,
    reviews: 156,
    slug: "gokarna-murudeshwar-trip",
    highlights: [
  "Mahabaleshwar Temple" ,		
	"Mirjan Fort",		
	"Om Beach",		
	"Kudle Beach",		
	"Murudeshwar - Shiva Statue",		
	"Honnavara Backwaters"		

    ],
    location: "450km from Bangalore",
    category: "Two Day Trip",
    fullDescription:
      "Escape to the pristine coastline of Karnataka with our Gokarna-Murudeshwar trip. This carefully curated 2-day journey takes you through untouched beaches, ancient temples, and offers the perfect mix of relaxation and adventure along the Arabian Sea.",    itinerary: [
      { time: "Day 1 - 05:30 AM", activity: "Journey to Gokarna from Bangalore" },
      { time: "12:00 PM", activity: "Arrive in Gokarna & check-in" },
      { time: "01:00 PM", activity: "Lunch at beachside restaurant" },
      { time: "02:30 PM", activity: "Visit Gokarna Main Beach & Temple" },
      { time: "04:00 PM", activity: "Trek to Paradise Beach via Half Moon Beach" },
      { time: "06:00 PM", activity: "Sunset viewing at Paradise Beach" },
      { time: "08:00 PM", activity: "Beach bonfire & dinner" },
      { time: "Day 2 - 07:00 AM", activity: "Breakfast & check-out" },
      { time: "08:30 AM", activity: "Travel to Murudeshwar" },
      { time: "10:00 AM", activity: "Visit Murudeshwar Temple & Shiva statue" },
      { time: "11:30 AM", activity: "Explore Murudeshwar Beach" },
      { time: "01:00 PM", activity: "Lunch with sea view" },
      { time: "02:30 PM", activity: "Optional water sports activities" },
      { time: "04:00 PM", activity: "Departure to Bangalore" },
      { time: "10:00 PM", activity: "Arrive in Bangalore" },
    ],
    pickupPoints: [
      "05:30 AM - Gopalan Arcade, RR Nagar",
      "05:45 AM - Kathriguppe Circle, Kathriguppe",
      "06:00 AM - BMTC Bus Stop, Banashankari",
      "06:20 AM - Udupi Garden Signal, BTM Layout",
      "06:30 AM - Bus Stop, Silk Board",
      "07:00 AM - Shell Petrol Pump, Bellandur",
      "07:30 AM - Opp. Kalamandir, Marathahalli",
      "07:50 AM - HP Petrol Pump, Tin Factory",
      "08:00 AM - Opp. Esteem Mall, Hebbal",
    ],
    inclusions: [
      "Comfortable AC vehicle for round-trip transportation",
      "1 night beach accommodation",
      "All meals (2 breakfast, 2 lunch, 1 dinner)",
      "Professional tour guide",
      "Beach trekking guide",
      "Temple entry fees",
      "Beach bonfire arrangement",
    ],
    exclusions: [
      "Water sports activities (optional)",
      "Personal expenses and shopping",
      "Insurance or items not listed under inclusions",
      "Tips for guides and drivers",
      "Any additional meals or beverages",
    ],
    whatToBring: [
      "Valid ID proof (mandatory)",
      "Comfortable beachwear and trekking shoes",
      "Swimwear and beach towel",
      "Sunscreen and sunglasses",
      "Camera for photography",
      "Personal medication",
      "Change of clothes",
      "Power bank and chargers",
    ],
  },
  {
    id: 9,
    title: "Chikmagalur Trip",
    description:
      "Immerse yourself in the coffee capital of India with lush plantations, misty mountains, and serene landscapes in this refreshing 2-day retreat.",
    image:
      "https://images.unsplash.com/photo-1526392060635-9d6019884377?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    price: "₹3,999",
    originalPrice: "₹4,299",
    duration: "2 Days / 1 Night",
    difficulty: "Easy",
    groupSize: "15-20",
    rating: 4.7,
    reviews: 108,
    slug: "chikmagalur-trip",
    highlights: [
      "Mullayanagiri Peak - Highest peak in Karnataka",
      "Coffee plantation tours and tasting sessions",
      "Hebbe Falls - A spectacular waterfall in the wilderness",
      "Baba Budangiri - Sacred hills with stunning views",
      "Authentic Malnad cuisine experience"
    ],
    location: "240km from Bangalore",
    category: "Two Day Trip",
    fullDescription:
      "Discover the enchanting hill station of Chikmagalur, known as the coffee capital of India. This 2-day journey takes you through aromatic coffee plantations, misty mountains, cascading waterfalls, and offers a perfect escape into nature's embrace.",    itinerary: [
      { time: "Day 1 - 06:00 AM", activity: "Journey to Chikmagalur from Bangalore" },
      { time: "10:30 AM", activity: "Arrive in Chikmagalur & check-in" },
      { time: "11:30 AM", activity: "Coffee plantation tour & tasting" },
      { time: "01:00 PM", activity: "Traditional Malnad lunch" },
      { time: "02:30 PM", activity: "Visit Hebbe Falls" },
      { time: "05:00 PM", activity: "Explore local markets" },
      { time: "07:00 PM", activity: "Dinner & overnight stay" },
      { time: "Day 2 - 06:00 AM", activity: "Early breakfast & check-out" },
      { time: "07:00 AM", activity: "Drive to Mullayanagiri Peak" },
      { time: "08:30 AM", activity: "Trek to highest point in Karnataka" },
      { time: "10:00 AM", activity: "Visit Baba Budangiri" },
      { time: "12:00 PM", activity: "Lunch at hill station" },
      { time: "01:30 PM", activity: "Photography & relaxation time" },
      { time: "02:30 PM", activity: "Departure to Bangalore" },
      { time: "07:00 PM", activity: "Arrive in Bangalore" },
    ],
    pickupPoints: [
      "06:00 AM - Gopalan Arcade, RR Nagar",
      "06:15 AM - Kathriguppe Circle, Kathriguppe",
      "06:30 AM - BMTC Bus Stop, Banashankari",
      "06:50 AM - Udupi Garden Signal, BTM Layout",
      "07:00 AM - Bus Stop, Silk Board",
      "07:30 AM - Shell Petrol Pump, Bellandur",
      "08:00 AM - Opp. Kalamandir, Marathahalli",
      "08:20 AM - HP Petrol Pump, Tin Factory",
      "08:30 AM - Opp. Esteem Mall, Hebbal",
    ],
    inclusions: [
      "Comfortable round-trip transportation",
      "1 night accommodation in Chikmagalur",
      "All meals (2 breakfast, 2 lunch, 1 dinner)",
      "Coffee plantation tour with tasting",
      "Professional tour guide",
      "Entry fees to all attractions",
    ],
    exclusions: [
      "Personal expenses and shopping",
      "Adventure activities not mentioned",
      "Insurance or items not listed under inclusions",
      "Tips for guides and drivers",
    ],
    whatToBring: [
      "Valid ID proof (mandatory)",
      "Comfortable trekking shoes",
      "Warm clothes for early morning",
      "Camera for photography",
      "Personal medication",
      "Umbrella or raincoat",      "Power bank and chargers",
    ],
  },
  {
    id: 10,
    title: "Wayanad Adventure",
    description:
      "Discover the lush green haven of Kerala with misty hills, waterfalls, and wildlife. Experience ancient caves, spice plantations, and thrilling adventure activities.",
    image:
      "/images/mountains/wayanad.jpg",
    price: "₹4,999",
    originalPrice: "₹5,499",
    duration: "2 Days / 1 Night",
    difficulty: "Easy",
    groupSize: "15-20",
    rating: 4.7,
    reviews: 92,
    slug: "wayanad-adventure",
    highlights: [
      "Edakkal Caves - Ancient petroglyphs and historical significance",
      "Banasura Dam - Largest earthen dam in India",
      "900 Kandi Bridge - Scenic mountain bridge experience",
      "Soochipara Waterfalls - Three-tiered spectacular waterfall",
      "Adventure activities: ziplining, giant swing, sky-cycling"
    ],
    location: "280km from Bangalore",
    category: "Two Day Trip",
    fullDescription:
      "Wayanad is a lush green haven in Kerala, known for its misty hills, waterfalls, and wildlife. From scenic treks to ancient caves and spice plantations, it offers a perfect mix of nature and culture. An ideal getaway for adventure seekers and peace lovers alike, Wayanad never disappoints.",    itinerary: [
      { time: "Day 1 - 05:30 AM", activity: "Journey to Wayanad from Bangalore" },
      { time: "11:30 AM", activity: "Arrive in Wayanad & check-in" },
      { time: "12:30 PM", activity: "Lunch at local restaurant" },
      { time: "02:00 PM", activity: "Visit Edakkal Caves" },
      { time: "04:00 PM", activity: "Explore 900 Kandi Bridge" },
      { time: "06:00 PM", activity: "Sunset viewing and photography" },
      { time: "07:30 PM", activity: "Dinner & overnight stay" },
      { time: "Day 2 - 07:00 AM", activity: "Breakfast & check-out" },
      { time: "08:30 AM", activity: "Visit Banasura Dam" },
      { time: "10:30 AM", activity: "Adventure activities (ziplining, giant swing)" },
      { time: "12:30 PM", activity: "Visit Soochipara Waterfalls" },
      { time: "02:00 PM", activity: "Lunch & departure to Bangalore" },
      { time: "08:00 PM", activity: "Arrive in Bangalore" },
    ],
    pickupPoints: [
      "05:30 AM - Gopalan Arcade, RR Nagar",
      "05:45 AM - Kathriguppe Circle, Kathriguppe",
      "06:00 AM - BMTC Bus Stop, Banashankari",
      "06:20 AM - Udupi Garden Signal, BTM Layout",
      "06:30 AM - Bus Stop, Silk Board",
      "07:00 AM - Shell Petrol Pump, Bellandur",
      "07:30 AM - Opp. Kalamandir, Marathahalli",
      "07:50 AM - HP Petrol Pump, Tin Factory",
      "08:00 AM - Opp. Esteem Mall, Hebbal",
    ],
    inclusions: [
      "Comfortable AC vehicle for round-trip transportation",
      "1 night accommodation in Wayanad",
      "All meals (2 breakfast, 2 lunch, 1 dinner)",
      "Professional tour guide",
      "Entry fees to all attractions",
      "Adventure activity charges",
    ],
    exclusions: [
      "Personal expenses and shopping",
      "Additional adventure activities not mentioned",
      "Insurance or items not listed under inclusions",
      "Tips for guides and drivers",
    ],
    whatToBring: [
      "Valid ID proof (mandatory)",
      "Comfortable trekking shoes",
      "Light cotton clothes and warm jacket",
      "Camera for photography",
      "Personal medication",
      "Umbrella or raincoat",
      "Power bank and chargers",
      "Swimwear for water activities",
    ],
  },
  {
    id: 11,
    title: "Ooty Adventure",
    description:
      "Escape to the Queen of Hill Stations with misty mountains, tea gardens, and colonial charm. Experience the famous toy train, botanical gardens, and scenic lakes.",
    image:
      "/images/mountains/ooty.jpg",
    price: "₹5,500",
    originalPrice: "₹6,000",
    duration: "2 Days / 1 Night",
    difficulty: "Easy",
    groupSize: "20-25",
    rating: 4.5,
    reviews: 112,
    slug: "ooty-adventure",
    highlights: [
      "Nilgiri Mountain Railway - UNESCO World Heritage toy train",
      "Botanical Gardens - Rare plants and fossil tree trunk",
      "Ooty Lake - Boating and scenic beauty",
      "Doddabetta Peak - Highest point in Nilgiris",
      "Tea Museum and plantation tours"
    ],
    location: "270km from Bangalore",
    category: "Two Day Trip",
    fullDescription:
      "Known as the 'Queen of Hill Stations,' Ooty offers a perfect blend of natural beauty and colonial heritage. With its misty mountains, sprawling tea gardens, and pleasant climate, Ooty provides an ideal retreat from city life with attractions like the famous toy train and scenic viewpoints.",    itinerary: [
      { time: "Day 1 - 05:30 AM", activity: "Journey to Ooty from Bangalore" },
      { time: "11:00 AM", activity: "Arrive in Ooty & check-in" },
      { time: "12:00 PM", activity: "Lunch at hill station restaurant" },
      { time: "01:30 PM", activity: "Visit Botanical Gardens" },
      { time: "03:30 PM", activity: "Ooty Lake boating experience" },
      { time: "05:00 PM", activity: "Explore local markets and shopping" },
      { time: "07:00 PM", activity: "Dinner & overnight stay" },
      { time: "Day 2 - 07:00 AM", activity: "Breakfast & check-out" },
      { time: "08:30 AM", activity: "Nilgiri Mountain Railway (Toy Train) experience" },
      { time: "10:30 AM", activity: "Visit Doddabetta Peak" },
      { time: "12:00 PM", activity: "Tea Museum and plantation tour" },
      { time: "01:30 PM", activity: "Lunch & departure to Bangalore" },
      { time: "07:30 PM", activity: "Arrive in Bangalore" },
    ],
    pickupPoints: [
      "05:30 AM - Gopalan Arcade, RR Nagar",
      "05:45 AM - Kathriguppe Circle, Kathriguppe",
      "06:00 AM - BMTC Bus Stop, Banashankari",
      "06:20 AM - Udupi Garden Signal, BTM Layout",
      "06:30 AM - Bus Stop, Silk Board",
      "07:00 AM - Shell Petrol Pump, Bellandur",
      "07:30 AM - Opp. Kalamandir, Marathahalli",
      "07:50 AM - HP Petrol Pump, Tin Factory",
      "08:00 AM - Opp. Esteem Mall, Hebbal",
    ],
    inclusions: [
      "Comfortable AC vehicle for round-trip transportation",
      "1 night accommodation in Ooty",
      "All meals (2 breakfast, 2 lunch, 1 dinner)",
      "Professional tour guide",
      "Toy train tickets",
      "Entry fees to all attractions",
      "Boating charges at Ooty Lake",
    ],
    exclusions: [
      "Personal expenses and shopping",
      "Additional activities not mentioned",
      "Insurance or items not listed under inclusions",
      "Tips for guides and drivers",
    ],
    whatToBring: [
      "Valid ID proof (mandatory)",
      "Warm clothes (jackets, sweaters)",
      "Comfortable walking shoes",
      "Camera for photography",
      "Personal medication",
      "Umbrella or raincoat",
      "Power bank and chargers",
    ],
  },
  {
    id: 12,
    title: "Dandeli Adventure",
    description:
      "Experience the ultimate adrenaline rush with white water rafting, jungle safaris, and adventure sports in Karnataka's premier adventure destination.",
    image:
      "/images/mountains/dandeli.jpg",
    price: "₹4,999",
    originalPrice: "₹5,499",
    duration: "2 Days / 1 Night",
    difficulty: "Moderate",
    groupSize: "15-20",
    rating: 4.8,
    reviews: 104,
    slug: "dandeli-adventure",
    highlights: [
      "White water rafting on Kali River - Grade 2 & 3 rapids",
      "Jungle safari in Dandeli Wildlife Sanctuary",
      "River crossing and kayaking adventures",
      "Night camping under the stars",
      "Adventure activities: zip-lining, rope climbing, rock climbing"
    ],
    location: "450km from Bangalore",
    category: "Two Day Trip",
    fullDescription:
      "Dandeli is Karnataka's adventure capital, offering thrilling white water rafting, wildlife encounters, and numerous adventure sports. Set amidst dense forests along the Kali River, it's perfect for adrenaline junkies and nature lovers seeking an action-packed weekend getaway.",    itinerary: [
      { time: "Day 1 - 05:30 AM", activity: "Journey to Dandeli from Bangalore" },
      { time: "12:00 PM", activity: "Arrive in Dandeli & check-in to jungle resort" },
      { time: "01:00 PM", activity: "Lunch at riverside restaurant" },
      { time: "02:30 PM", activity: "White water rafting on Kali River" },
      { time: "04:30 PM", activity: "River crossing and kayaking" },
      { time: "06:00 PM", activity: "Evening tea and relaxation" },
      { time: "07:30 PM", activity: "Campfire, dinner & overnight stay" },
      { time: "Day 2 - 06:30 AM", activity: "Jungle safari in Dandeli Wildlife Sanctuary" },
      { time: "08:30 AM", activity: "Breakfast at resort" },
      { time: "10:00 AM", activity: "Adventure activities (zip-lining, rope climbing)" },
      { time: "12:00 PM", activity: "Check-out & lunch" },
      { time: "01:30 PM", activity: "Departure to Bangalore" },
      { time: "07:30 PM", activity: "Arrive in Bangalore" },
    ],
    pickupPoints: [
      "05:30 AM - Gopalan Arcade, RR Nagar",
      "05:45 AM - Kathriguppe Circle, Kathriguppe",
      "06:00 AM - BMTC Bus Stop, Banashankari",
      "06:20 AM - Udupi Garden Signal, BTM Layout",
      "06:30 AM - Bus Stop, Silk Board",
      "07:00 AM - Shell Petrol Pump, Bellandur",
      "07:30 AM - Opp. Kalamandir, Marathahalli",
      "07:50 AM - HP Petrol Pump, Tin Factory",
      "08:00 AM - Opp. Esteem Mall, Hebbal",
    ],
    inclusions: [
      "Comfortable AC vehicle for round-trip transportation",
      "1 night accommodation in jungle resort",
      "All meals (2 breakfast, 2 lunch, 1 dinner)",
      "Professional adventure guides",
      "White water rafting equipment and safety gear",
      "Jungle safari charges",
      "All adventure activity charges",
    ],
    exclusions: [
      "Personal expenses and shopping",
      "Additional activities not mentioned",
      "Insurance or items not listed under inclusions",
      "Tips for guides and drivers",
      "Any medical expenses",
    ],
    whatToBring: [
      "Valid ID proof (mandatory)",
      "Quick-dry clothes and extra set",
      "Sports shoes with good grip",
      "Swimwear for water activities",
      "Waterproof bag for valuables",
      "Personal medication",
      "Power bank and chargers",
      "Sunscreen and sunglasses",
    ],
  },
  {
    id: 13,
    title: "Kudremukh Trek",
    description:
      "Conquer the 'Horse-faced Peak' of Karnataka with this challenging yet rewarding trek through pristine forests, grasslands, and breathtaking mountain views.",
    image:
      "/images/mountains/kudremukh.jpg",
    price: "₹3,899",
    originalPrice: "₹4,999",
    duration: "2 Days / 1 Night",
    difficulty: "Moderate to Difficult",
    groupSize: "12-15",
    rating: 4.9,
    reviews: 87,
    slug: "kudremukh-trek",
    highlights: [
      "Trek to Kudremukh Peak (1,894m) - Horse-faced mountain",
      "Pristine Shola forests and rolling grasslands",
      "Spectacular sunrise and sunset views",
      "Wildlife spotting in Kudremukh National Park",
      "Stream crossings and natural swimming pools"
    ],
    location: "320km from Bangalore",
    category: "Two Day Trip",
    fullDescription:
      "Kudremukh, meaning 'Horse Face' in Kannada, is one of Karnataka's most beautiful and challenging treks. Located in the Western Ghats, this trek offers pristine forests, rolling grasslands, and spectacular mountain views. Perfect for experienced trekkers seeking a wilderness adventure.",    itinerary: [
      { time: "Day 1 - 05:30 AM", activity: "Journey & Base Camp from Bangalore" },
      { time: "11:00 AM", activity: "Arrive at Kudremukh base village" },
      { time: "11:30 AM", activity: "Trek briefing and equipment check" },
      { time: "12:00 PM", activity: "Begin trek to base camp" },
      { time: "01:30 PM", activity: "Lunch en route (packed meal)" },
      { time: "04:00 PM", activity: "Reach base camp & set up tents" },
      { time: "06:00 PM", activity: "Evening tea and sunset viewing" },
      { time: "08:00 PM", activity: "Dinner & overnight camping" },
      { time: "Day 2 - 05:00 AM", activity: "Early morning tea & trek preparation" },
      { time: "05:30 AM", activity: "Summit push to Kudremukh Peak" },
      { time: "08:30 AM", activity: "Reach summit & enjoy panoramic views" },
      { time: "10:00 AM", activity: "Begin descent to base camp" },
      { time: "12:00 PM", activity: "Pack up camp & lunch" },
      { time: "01:30 PM", activity: "Trek back to base village" },
      { time: "03:00 PM", activity: "Departure to Bangalore" },
      { time: "08:00 PM", activity: "Arrive in Bangalore" },
    ],
    pickupPoints: [
      "05:30 AM - Gopalan Arcade, RR Nagar",
      "05:45 AM - Kathriguppe Circle, Kathriguppe",
      "06:00 AM - BMTC Bus Stop, Banashankari",
      "06:20 AM - Udupi Garden Signal, BTM Layout",
      "06:30 AM - Bus Stop, Silk Board",
      "07:00 AM - Shell Petrol Pump, Bellandur",
      "07:30 AM - Opp. Kalamandir, Marathahalli",
      "07:50 AM - HP Petrol Pump, Tin Factory",
      "08:00 AM - Opp. Esteem Mall, Hebbal",
    ],
    inclusions: [
      "Comfortable vehicle for round-trip transportation",
      "1 night camping accommodation",
      "All meals (2 breakfast, 2 lunch, 1 dinner)",
      "Professional trek guide and support staff",
      "Camping equipment (tents, sleeping bags)",
      "Forest permits and entry fees",
      "First aid kit and safety equipment",
    ],
    exclusions: [
      "Personal trekking gear (available on rent)",
      "Personal expenses",
      "Insurance or items not listed under inclusions",
      "Tips for guides and support staff",
      "Any medical expenses",
    ],
    whatToBring: [
      "Valid ID proof (mandatory)",
      "Trekking shoes with good ankle support",
      "Comfortable trekking clothes",
      "Warm clothes for night camping",
      "Rain gear and poncho",
      "Personal water bottles",
      "Headlamp or flashlight",
      "Personal medication",
      "Energy snacks and dry fruits",
    ],
  },
  {
    id: 14,
    title: "Netravati Trek",
    description:
      "Experience one of Karnataka's most scenic and challenging treks through dense forests, river crossings, and stunning peak views in the Western Ghats.",
    image:
      "/images/mountains/netravati.jpg",
    price: "₹3,899",
    originalPrice: "₹4,799",
    duration: "2 Days / 1 Night",
    difficulty: "Moderate to Difficult",
    groupSize: "10-15",
    rating: 4.8,
    reviews: 73,
    slug: "netravati-trek",
    highlights: [
      "Trek to Netravati Peak through pristine Western Ghats",
      "Multiple river crossings and natural pools",
      "Dense evergreen forest trails",
      "Spectacular sunrise views from the summit",
      "Wildlife spotting and bird watching opportunities"
    ],
    location: "300km from Bangalore",
    category: "Two Day Trip",
    fullDescription:
      "The Netravati Trek is one of the most scenic and challenging treks in Karnataka's Western Ghats. Known for its pristine forests, multiple river crossings, and spectacular summit views, this trek offers an authentic wilderness experience for adventure enthusiasts.",    itinerary: [
      { time: "Day 1 - 05:30 AM", activity: "Journey & Forest Trek from Bangalore" },
      { time: "10:30 AM", activity: "Arrive at Netravati base point" },
      { time: "11:00 AM", activity: "Trek briefing and safety instructions" },
      { time: "11:30 AM", activity: "Begin trek through dense forests" },
      { time: "01:00 PM", activity: "Lunch break at riverside" },
      { time: "02:00 PM", activity: "Continue trek with river crossings" },
      { time: "05:00 PM", activity: "Reach camping site & set up tents" },
      { time: "07:00 PM", activity: "Evening campfire & dinner" },
      { time: "Day 2 - 05:00 AM", activity: "Early morning tea & preparation" },
      { time: "05:30 AM", activity: "Final ascent to Netravati Peak" },
      { time: "07:30 AM", activity: "Reach summit & sunrise viewing" },
      { time: "09:00 AM", activity: "Begin descent journey" },
      { time: "12:00 PM", activity: "Lunch en route" },
      { time: "02:30 PM", activity: "Reach base point" },
      { time: "03:00 PM", activity: "Departure to Bangalore" },
      { time: "07:30 PM", activity: "Arrive in Bangalore" },
    ],
    pickupPoints: [
      "05:30 AM - Gopalan Arcade, RR Nagar",
      "05:45 AM - Kathriguppe Circle, Kathriguppe",
      "06:00 AM - BMTC Bus Stop, Banashankari",
      "06:20 AM - Udupi Garden Signal, BTM Layout",
      "06:30 AM - Bus Stop, Silk Board",
      "07:00 AM - Shell Petrol Pump, Bellandur",
      "07:30 AM - Opp. Kalamandir, Marathahalli",
      "07:50 AM - HP Petrol Pump, Tin Factory",
      "08:00 AM - Opp. Esteem Mall, Hebbal",
    ],
    inclusions: [
      "Round-trip transportation from Bangalore",
      "1 night camping in forest",
      "All meals (2 breakfast, 2 lunch, 1 dinner)",
      "Experienced trek guide and support team",
      "Camping equipment and safety gear",
      "Forest permits and entry fees",
      "First aid kit and emergency support",
    ],
    exclusions: [
      "Personal trekking equipment",
      "Personal expenses and tips",
      "Insurance coverage",
      "Any items not mentioned in inclusions",
      "Medical expenses if required",
    ],
    whatToBring: [
      "Valid government ID proof",
      "Waterproof trekking shoes",
      "Quick-dry trekking clothes",
      "Warm clothes for night camping",
      "Rain gear and waterproof covers",
      "Personal water bottles (2-3 liters)",
      "Headlamp with extra batteries",
      "Personal medication",
      "Energy bars and dry fruits",
    ],
  },
  {
    id: 15,
    title: "Bandaje Falls Trek",
    description:
      "Discover the hidden gem of Karnataka with this adventurous trek to one of the most spectacular waterfalls in the Western Ghats, surrounded by pristine forests.",
    image:
      "https://images.unsplash.com/photo-1454982523318-4b6396f39d3a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
    price: "₹3,899",
    originalPrice: "₹4,299",
    duration: "2 Days / 1 Night",
    difficulty: "Moderate",
    groupSize: "12-18",
    rating: 4.6,
    reviews: 91,
    slug: "bandaje-falls-trek",
    highlights: [
      "Trek to spectacular Bandaje Falls (200ft waterfall)",
      "Dense Western Ghats forest trail",
      "Natural swimming pools and rock slides",
      "Camping under the stars in pristine wilderness",
      "Photography opportunities with stunning landscapes"
    ],
    location: "280km from Bangalore",
    category: "Two Day Trip",
    fullDescription:
      "The Bandaje Falls Trek takes you through the pristine forests of the Western Ghats to one of Karnataka's most beautiful waterfalls. This moderate trek offers stunning natural beauty, camping experiences, and the refreshing experience of swimming in natural pools beneath the magnificent 200-foot waterfall.",    itinerary: [
      { time: "Day 1 - 06:00 AM", activity: "Journey to Bandaje from Bangalore" },
      { time: "11:00 AM", activity: "Arrive at trek starting point" },
      { time: "11:30 AM", activity: "Trek briefing and equipment distribution" },
      { time: "12:00 PM", activity: "Begin trek through forest trails" },
      { time: "02:00 PM", activity: "Lunch break in forest clearing" },
      { time: "03:00 PM", activity: "Continue trek towards waterfall" },
      { time: "05:30 PM", activity: "Reach Bandaje Falls & camping site" },
      { time: "07:00 PM", activity: "Set up camp & evening activities" },
      { time: "08:30 PM", activity: "Campfire dinner under the stars" },
      { time: "Day 2 - 06:30 AM", activity: "Wake up call & morning tea" },
      { time: "07:00 AM", activity: "Explore waterfall & natural pools" },
      { time: "09:00 AM", activity: "Swimming and photography session" },
      { time: "10:30 AM", activity: "Pack up camp & breakfast" },
      { time: "11:30 AM", activity: "Begin return trek" },
      { time: "01:30 PM", activity: "Lunch at base point" },
      { time: "02:30 PM", activity: "Departure to Bangalore" },
      { time: "07:00 PM", activity: "Arrive in Bangalore" },
    ],
    pickupPoints: [
      "06:00 AM - Gopalan Arcade, RR Nagar",
      "06:15 AM - Kathriguppe Circle, Kathriguppe",
      "06:30 AM - BMTC Bus Stop, Banashankari",
      "06:50 AM - Udupi Garden Signal, BTM Layout",
      "07:00 AM - Bus Stop, Silk Board",
      "07:30 AM - Shell Petrol Pump, Bellandur",
      "08:00 AM - Opp. Kalamandir, Marathahalli",
      "08:20 AM - HP Petrol Pump, Tin Factory",
      "08:30 AM - Opp. Esteem Mall, Hebbal",
    ],
    inclusions: [
      "Round-trip transportation from Bangalore",
      "1 night camping near waterfall",
      "All meals (2 breakfast, 2 lunch, 1 dinner)",
      "Professional trek guide",
      "Camping equipment (tents, sleeping bags)",
      "Safety equipment and first aid",
      "Forest permits and entry fees",
    ],
    exclusions: [
      "Personal trekking gear",
      "Personal expenses and shopping",
      "Insurance coverage",
      "Tips for guides and support staff",
      "Any medical expenses",
    ],
    whatToBring: [
      "Valid photo ID proof",
      "Waterproof trekking shoes",
      "Quick-dry clothes and swimwear",
      "Warm clothes for night camping",
      "Rain protection gear",
      "Personal water bottles",
      "Waterproof bag for electronics",
      "Personal medication",
      "Towel and personal toiletries",
    ],
  },
];
