import { Trip } from "./types";

export const trips: Trip[] = [
  {
    id: 1,
    title: "Nandi Hills Sunrise Trek",
    description:
      "Witness the breathtaking sunrise from the historic Nandi Hills, perfect for photography enthusiasts and nature lovers.",
    image:
      "/images/11.jpeg", // Using a local image to avoid remote image issues
    price: "₹799",
    originalPrice: "₹999",
    duration: "1 Day",
    difficulty: "Easy",
    groupSize: "15-25",
    rating: 4.7,
    reviews: 89,
    slug: "nandi-hills-sunrise-trek",
    highlights: [
      "Ideal for all trekkers - Beginners to seasoned hikers",
      "Ancient hill fort trail with scenic viewpoints",
      "Budget-friendly adventure",
      "Mesmerizing sunrise views over the landscape",
    ],
    location: "60km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Wake up to an unforgettable adventure! The Nandi Hills Sunrise Trek is one of the most sought-after quick getaways from Bangalore – perfect for beginners, nature lovers, and anyone craving fresh mountain air and mesmerizing sunrise views. This iconic hill fort offers breathtaking panoramic vistas, ancient temples, and is accessible to trekkers of all experience levels.",
    itinerary: [
      { time: "Day 0", activity: "Departure from Bengaluru at selected pickup points" },
      { time: "11:15 PM", activity: "Gopalan Arcade, RR Nagar" },
      { time: "11:30 PM", activity: "Kathriguppe Circle, Kathriguppe" },
      { time: "11:45 PM", activity: "BMTC Bus Stop, Banashankari" },
      { time: "12:05 AM", activity: "Udupi Garden Signal, BTM Layout" },
      { time: "12:15 AM", activity: "Bus Stop, Silk Board" },
      { time: "12:45 AM", activity: "Shell Petrol Pump, Bellandur" },
      { time: "01:15 AM", activity: "Opp. Kalamandir, Marathahalli" },
      { time: "01:35 AM", activity: "HP Petrol Pump, Tin Factory" },
      { time: "01:45 AM", activity: "Opp. Esteem Mall, Hebbal" },
      { time: "02:00 AM", activity: "Reach Nandi base, rest or stargaze" },
      { time: "03:30 AM", activity: "Start trek after orientation" },
      { time: "05:30 AM", activity: "Reach summit & enjoy the sunrise" },
      { time: "07:00 AM", activity: "Begin descent" },
      { time: "09:00 AM", activity: "Reach base & start return journey" },
      { time: "09:30 AM", activity: "Visit Bhoga Nandishwara Temple & breakfast stop (self-funded)" },
      { time: "11:00 AM", activity: "Drop-off at your original pickup points in Bangalore" },
    ],
    inclusions: [
      "Comfortable round-trip transportation from Bangalore",
      "Forest or trekking guide",
      "Trek lead from the Abhitrip Team",
      "Access to first-aid kit",
      "Forest permit if any (INCLUDED)",
    ],
    exclusions: [
      "Meals (breakfast/snacks)",
      "Bottled water or other personal purchases",
      "Insurance or items not listed under inclusions",
    ],
    whatToBring: [
      "A photocopy of your Aadhar/Voter ID (mandatory)",
      "Small backpack (to carry essentials)",
      "Water bottles – 1–2 liters",
      "Raincoat/poncho or bag cover (in case of rain)",
      "Trekking shoes with good grip + extra socks",
      "Torch/headlamp (required for night trek)",
      "Power bank",
      "Snacks (dry fruits, energy bars, etc.)",
      "Any personal medication",
    ],
  },
  {
    id: 2,
    title: "Coorg Trip – The Scotland of India",
    description:
      "Discover the lush beauty and cultural richness of Coorg – often hailed as the 'Scotland of India.' From majestic viewpoints and roaring waterfalls to spiritual sanctuaries and elephant encounters, this 2-day escape is crafted for nature lovers, photographers, and adventure seekers. Ideal for solo travelers, friends, and weekend wanderers.",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/84fc1cbf7bd4a97d9893abfdc41e0f9d%20%281%29.jpg-tniux34eccmxX3eI266tYCVwuB2QK3.jpeg",
    price: "₹3,999",
    originalPrice: "₹4,499",
    duration: "2 Days / 1 Night",
    difficulty: "Easy",
    groupSize: "15-20",
    rating: 4.8,
    reviews: 124,
    slug: "coorg-trip",
    highlights: [
      "Mandalpatti View Point - Panoramic vistas of Coorg's verdant landscapes",
      "Abbey Falls - A roaring cascade in the heart of nature",
      "Raja Seat - Sunset views that steal your breath",
      "Harangi Elephant Camp - Close encounter with gentle giants",
      "Namdroling Monastery - Golden Temple and Tibetan culture"
    ],
    location: "250km from Bangalore",
    category: "Two Day Trip",
    fullDescription:
      "Discover the lush beauty and cultural richness of Coorg – often hailed as the 'Scotland of India.' From majestic viewpoints and roaring waterfalls to spiritual sanctuaries and elephant encounters, this 2-day escape is crafted for nature lovers, photographers, and adventure seekers. Ideal for solo travelers, friends, and weekend wanderers.",
    itinerary: [
      { time: "Day 1", activity: "Departure from Bangalore" },
      { time: "07:00 AM", activity: "Pickup from Bangalore" },
      { time: "11:00 AM", activity: "Arrive at Coorg" },
      { time: "11:30 AM", activity: "Visit Mandalpatti View Point" },
      { time: "01:00 PM", activity: "Abbey Falls exploration" },
      { time: "02:30 PM", activity: "Lunch at a local Coorgi restaurant" },
      { time: "04:00 PM", activity: "Raja Seat visit" },
      { time: "06:00 PM", activity: "Check-in at the hotel/homestay" },
      { time: "07:30 PM", activity: "Dinner at the hotel/homestay" },
      { time: "Day 2", activity: "Coorg exploration and return" },
      { time: "07:00 AM", activity: "Breakfast at the hotel/homestay" },
      { time: "08:00 AM", activity: "Visit Harangi Elephant Camp" },
      { time: "10:00 AM", activity: "Explore Namdroling Monastery" },
      { time: "12:00 PM", activity: "Lunch at a local restaurant" },
      { time: "02:00 PM", activity: "Start return journey to Bangalore" },
      { time: "06:00 PM", activity: "Drop at pickup points in Bangalore" },
    ],
    pickupPoints: [
      "Gopalan Arcade, RR Nagar",
      "Kathriguppe Circle, Kathriguppe",
      "BMTC Bus Stop, Banashankari",
      "Udupi Garden Signal, BTM Layout",
      "Bus Stop, Silk Board",
      "Shell Petrol Pump, Bellandur",
      "Opp. Kalamandir, Marathahalli",
      "HP Petrol Pump, Tin Factory",
      "Opp. Esteem Mall, Hebbal"
    ],
    inclusions: [
      "Non-A/C round-trip transport from Bangalore",
      "Accommodation for 1 night",
      "Breakfast and dinner",
      "Lunch on Day 1",
      "Entry fees to attractions",
      "Professional guide",
    ],
    exclusions: [
      "Any kind of insurance",
      "Personal expenses",
      "Additional meals",
      "Travel insurance",
      "Tips for guide",
    ],
    whatToBring: [
      "Comfortable walking shoes",
      "Water bottle",
      "Camera",
      "Light jacket",
      "Sunscreen",
      "Personal medication",
    ],
  },
  {
    id: 3,
    title: "Chikmagalur Hill Station Retreat",
    description:
      "Explore the royal heritage of Mysore with a visit to the magnificent Mysore Palace and the sacred Chamundi Hill.",
    image:
      "https://images.unsplash.com/photo-1573674401446-87cae8d4d28e?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹1,099",
    originalPrice: "₹1,399",
    duration: "1 Day",
    difficulty: "Easy",
    groupSize: "15-30",
    rating: 4.6,
    reviews: 75,
    slug: "chikmagalur-trip",
    highlights: ["Mysore Palace", "Chamundi Hill", "Devaraja Market", "St. Philomena's Church"],
    location: "145km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Step into the regal past of Mysore on this enriching day tour. Marvel at the stunning architecture and opulent interiors of the Mysore Palace, a UNESCO World Heritage Site. Then, visit the sacred Chamundi Hill, home to the famous Chamundeshwari Temple. This tour is perfect for history buffs and spiritual seekers.",
    itinerary: [
      { time: "7:00 AM", activity: "Pickup from Bangalore" },
      { time: "9:30 AM", activity: "Arrive at Mysore Palace" },
      { time: "10:00 AM", activity: "Guided tour of Mysore Palace" },
      { time: "12:00 PM", activity: "Visit Chamundi Hill and temple" },
      { time: "1:30 PM", activity: "Lunch at a local restaurant" },
      { time: "3:00 PM", activity: "Explore Devaraja Market" },
      { time: "4:30 PM", activity: "Visit St. Philomena's Church" },
      { time: "6:00 PM", activity: "Return journey to Bangalore" },
      { time: "9:00 PM", activity: "Drop at pickup points" },
    ],
    inclusions: [
      "Non-A/C round-trip transport from Bangalore",
      "Palace entry fees",
      "Lunch",
      "Professional guide",
    ],
    exclusions: [
      "Any kind of insurance",
      "Personal expenses",
      "Additional meals",
      "Travel insurance",
      "Tips for guide",
    ],
    whatToBring: [
      "Comfortable walking shoes",
      "Water bottle",
      "Camera",
      "Light jacket",
      "Sunscreen",
      "Personal medication",
    ],
  },
  {
    id: 4,
    title: "Gokarna Beach Retreat",
    description:
      "Visit the serene beaches and ancient temples of Gokarna, a spiritual and coastal paradise.",
    image:
      "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    price: "₹1,299",
    originalPrice: "₹1,599",
    duration: "1 Day",
    difficulty: "Easy",
    groupSize: "15-30",
    rating: 4.5,
    reviews: 60,
    slug: "gokarna-murudeshwar-trip",
    highlights: ["Kumta Beach", "Mahabaleshwar Temple", "Mirjan Fort", "Om Beach"],
    location: "485km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Experience the spiritual and natural beauty of Gokarna on this delightful day tour. Visit the ancient Mahabaleshwar Temple, relax on the pristine beaches, and explore the historic Mirjan Fort. This tour is perfect for those seeking a peaceful getaway from the hustle and bustle of city life.",
    itinerary: [
      { time: "6:00 AM", activity: "Pickup from Bangalore" },
      { time: "10:30 AM", activity: "Arrive at Mahabaleshwar Temple" },
      { time: "11:30 AM", activity: "Visit Mirjan Fort" },
      { time: "1:00 PM", activity: "Lunch at a local restaurant" },
      { time: "2:30 PM", activity: "Relax at Kumta Beach" },
      { time: "4:00 PM", activity: "Visit Om Beach" },
      { time: "6:00 PM", activity: "Return journey to Bangalore" },
      { time: "10:00 PM", activity: "Drop at pickup points" },
    ],
    inclusions: [
      "Non-A/C round-trip transport from Bangalore",
      "Temple and fort entry fees",
      "Lunch",
      "Professional guide",
    ],
    exclusions: [
      "Any kind of insurance",
      "Personal expenses",
      "Additional meals",
      "Travel insurance",
      "Tips for guide",
    ],
    whatToBring: [
      "Comfortable clothing",
      "Water bottle",
      "Camera",
      "Swimwear and towel",
      "Sunscreen",
      "Personal medication",
    ],
  },
  {
    id: 5,
    title: "Kabini Wildlife Sanctuary Safari",
    description:
      "Embark on an exciting safari adventure in the Kabini Wildlife Sanctuary, home to diverse flora and fauna.",
    image:
      "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    price: "₹2,499",
    originalPrice: "₹2,999",
    duration: "1 Day",
    difficulty: "Moderate",
    groupSize: "10-20",
    rating: 4.9,
    reviews: 200,
    slug: "kabini-wildlife-sanctuary-safari",
    highlights: ["Wildlife safari", "Bird watching", "Nature trails", "Kabini River"],
    location: "220km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Experience the thrill of a wildlife safari in the pristine Kabini Wildlife Sanctuary. Home to elephants, tigers, leopards, and a variety of birds, Kabini offers an unforgettable wildlife experience. This tour includes a guided safari, nature walks, and bird watching, making it perfect for wildlife enthusiasts and photographers.",
    itinerary: [
      { time: "5:30 AM", activity: "Pickup from Bangalore" },
      { time: "8:30 AM", activity: "Arrive at Kabini Wildlife Sanctuary" },
      { time: "9:00 AM", activity: "Morning safari in the sanctuary" },
      { time: "12:00 PM", activity: "Lunch at the resort" },
      { time: "2:00 PM", activity: "Afternoon nature walk" },
      { time: "4:00 PM", activity: "Evening safari in the sanctuary" },
      { time: "7:00 PM", activity: "Return journey to Bangalore" },
      { time: "10:00 PM", activity: "Drop at pickup points" },
    ],
    inclusions: [
      "Non-A/C round-trip transport from Bangalore",
      "Safari permits",
      "Lunch",
      "Professional guide",
    ],
    exclusions: [
      "Any kind of insurance",
      "Personal expenses",
      "Additional meals",
      "Travel insurance",
      "Tips for guide",
    ],
    whatToBring: [
      "Comfortable clothing",
      "Water bottle",
      "Camera",
      "Binoculars",
      "Sunscreen",
      "Personal medication",
    ],
  },
  {
    id: 6,
    title: "Hampi Historical Tour",
    description:
      "Discover the ancient ruins and rich history of Hampi, a UNESCO World Heritage Site.",
    image:
      "https://images.unsplash.com/photo-1568605114967-8130f3a7a7a4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    price: "₹1,799",
    originalPrice: "₹2,199",
    duration: "1 Day",
    difficulty: "Moderate",
    groupSize: "10-25",
    rating: 4.7,
    reviews: 95,
    slug: "hampi-historical-tour",
    highlights: ["Vijaya Vittala Temple", "Virupaksha Temple", "Hampi Bazaar", "Matanga Hill"],
    location: "340km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Step back in time and explore the fascinating ruins of Hampi, once the capital of the Vijayanagara Empire. This tour takes you to the most iconic landmarks of Hampi, including the stunning Vijaya Vittala Temple and the ancient Virupaksha Temple. Enjoy a guided tour of the historical sites and learn about the rich heritage of this UNESCO World Heritage Site.",
    itinerary: [
      { time: "6:00 AM", activity: "Pickup from Bangalore" },
      { time: "10:00 AM", activity: "Arrive at Hampi" },
      { time: "10:30 AM", activity: "Visit Vijaya Vittala Temple" },
      { time: "12:00 PM", activity: "Explore Virupaksha Temple" },
      { time: "1:30 PM", activity: "Lunch at a local restaurant" },
      { time: "3:00 PM", activity: "Walk through Hampi Bazaar" },
      { time: "4:30 PM", activity: "Sunset view from Matanga Hill" },
      { time: "6:00 PM", activity: "Return journey to Bangalore" },
      { time: "10:00 PM", activity: "Drop at pickup points" },
    ],
    inclusions: [
      "Non-A/C round-trip transport from Bangalore",
      "Temple entry fees",
      "Lunch",
      "Professional guide",
    ],
    exclusions: [
      "Any kind of insurance",
      "Personal expenses",
      "Additional meals",
      "Travel insurance",
      "Tips for guide",
    ],
    whatToBring: [
      "Comfortable walking shoes",
      "Water bottle",
      "Camera",
      "Light jacket",
      "Sunscreen",
      "Personal medication",
    ],
  },
  {
    id: 7,
    title: "Chikmagalur Coffee and Spice Plantation Tour",
    description:
      "Explore the aromatic coffee and spice plantations of Chikmagalur and enjoy a day amidst nature.",
    image:
      "https://images.unsplash.com/photo-1521747116042-5a810fda9664?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    price: "₹1,699",
    originalPrice: "₹2,099",
    duration: "1 Day",
    difficulty: "Easy",
    groupSize: "10-20",
    rating: 4.8,
    reviews: 110,
    slug: "chikmagalur-coffee-spice-plantation-tour",
    highlights: ["Coffee plantation tour", "Spice garden visit", "Nature walk", "Scenic views"],
    location: "280km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Delight your senses with a tour of Chikmagalur's famous coffee and spice plantations. Learn about the cultivation and processing of coffee and spices, and enjoy the fresh mountain air and stunning views of the Western Ghats. This tour is a perfect escape for nature and coffee lovers.",
    itinerary: [
      { time: "6:30 AM", activity: "Pickup from Bangalore" },
      { time: "10:00 AM", activity: "Arrive at Chikmagalur plantation" },
      { time: "10:30 AM", activity: "Guided tour of coffee plantation" },
      { time: "12:00 PM", activity: "Visit spice garden" },
      { time: "1:30 PM", activity: "Lunch at a plantation homestay" },
      { time: "3:00 PM", activity: "Nature walk in the plantation" },
      { time: "5:00 PM", activity: "Return journey to Bangalore" },
      { time: "9:00 PM", activity: "Drop at pickup points" },
    ],
    inclusions: [
      "Non-A/C round-trip transport from Bangalore",
      "Plantation entry fees",
      "Lunch",
      "Professional guide",
    ],
    exclusions: [
      "Any kind of insurance",
      "Personal expenses",
      "Additional meals",
      "Travel insurance",
      "Tips for guide",
    ],
    whatToBring: [
      "Comfortable walking shoes",
      "Water bottle",
      "Camera",
      "Light jacket",
      "Sunscreen",
      "Personal medication",
    ],
  },
  {
    id: 8,
    title: "Sakleshpur Homestay and Trek",
    description:
      "Experience the beauty of Sakleshpur with a homestay and trek in the scenic Western Ghats.",
    image:
      "https://images.unsplash.com/photo-1514516874920-4f3f3c8e4f3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    price: "₹2,199",
    originalPrice: "₹2,699",
    duration: "1 Day",
    difficulty: "Moderate",
    groupSize: "10-15",
    rating: 4.7,
    reviews: 85,
    slug: "sakleshpur-homestay-trek",
    highlights: ["Homestay experience", "Trekking", "Coffee plantation visit", "Nature exploration"],
    location: "220km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Enjoy a perfect blend of adventure and relaxation with a homestay and trek in Sakleshpur. Explore the lush green landscapes, coffee plantations, and scenic viewpoints of the Western Ghats. This tour offers a unique opportunity to experience the local culture and hospitality of Karnataka.",
    itinerary: [
      { time: "6:00 AM", activity: "Pickup from Bangalore" },
      { time: "9:00 AM", activity: "Arrive at Sakleshpur homestay" },
      { time: "9:30 AM", activity: "Breakfast and orientation" },
      { time: "10:30 AM", activity: "Trek to Ettina Bhuja" },
      { time: "1:00 PM", activity: "Lunch at the homestay" },
      { time: "2:00 PM", activity: "Visit coffee plantation" },
      { time: "4:00 PM", activity: "Nature walk and bird watching" },
      { time: "6:00 PM", activity: "Campfire and dinner" },
      { time: "8:00 PM", activity: "Return journey to Bangalore" },
      { time: "11:00 PM", activity: "Drop at pickup points" },
    ],
    inclusions: [
      "Non-A/C round-trip transport from Bangalore",
      "Homestay accommodation",
      "All meals",
      "Trekking and plantation fees",
      "Professional guide",
    ],
    exclusions: [
      "Any kind of insurance",
      "Personal expenses",
      "Travel insurance",
      "Tips for guide",
    ],
    whatToBring: [
      "Comfortable trekking shoes",
      "Water bottle",
      "Camera",
      "Light jacket",
      "Sunscreen",
      "Personal medication",
    ],
  },
  {
    id: 9,
    title: "Kabini River Rafting and Wildlife Tour",
    description:
      "Experience the thrill of river rafting and the beauty of wildlife in the Kabini region.",
    image:
      "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    price: "₹2,999",
    originalPrice: "₹3,499",
    duration: "1 Day",
    difficulty: "Moderate",
    groupSize: "10-15",
    rating: 4.9,
    reviews: 150,
    slug: "kabini-river-rafting-wildlife-tour",
    highlights: ["River rafting", "Wildlife safari", "Bird watching", "Nature trails"],
    location: "220km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Get ready for an adrenaline-pumping adventure in the Kabini region. This tour combines the excitement of river rafting with the tranquility of a wildlife safari. Explore the rich biodiversity of the Kabini Wildlife Sanctuary and enjoy a thrilling rafting experience on the Kabini River.",
    itinerary: [
      { time: "6:00 AM", activity: "Pickup from Bangalore" },
      { time: "9:00 AM", activity: "Arrive at Kabini River base" },
      { time: "9:30 AM", activity: "Safety briefing and rafting gear allocation" },
      { time: "10:00 AM", activity: "River rafting on Kabini River" },
      { time: "1:00 PM", activity: "Lunch at a riverside restaurant" },
      { time: "2:30 PM", activity: "Wildlife safari in Kabini Wildlife Sanctuary" },
      { time: "5:30 PM", activity: "Return journey to Bangalore" },
      { time: "8:30 PM", activity: "Drop at pickup points" },
    ],
    inclusions: [
      "Non-A/C round-trip transport from Bangalore",
      "Rafting and safari permits",
      "Lunch",
      "Professional guide",
    ],
    exclusions: [
      "Any kind of insurance",
      "Personal expenses",
      "Additional meals",
      "Travel insurance",
      "Tips for guide",
    ],
    whatToBring: [
      "Quick-dry clothing",
      "Water bottle",
      "Camera",
      "Swimwear and towel",
      "Sunscreen",
      "Personal medication",
    ],
  },
  {
    id: 10,
    title: "Yercaud Hill Station Tour",
    description:
      "Escape to the serene Yercaud Hill Station and enjoy the cool climate and beautiful landscapes.",
    image:
      "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    price: "₹1,899",
    originalPrice: "₹2,299",
    duration: "1 Day",
    difficulty: "Easy",
    groupSize: "15-25",
    rating: 4.6,
    reviews: 70,
    slug: "yercaud-hill-station-tour",
    highlights: ["Pagoda Point", "Lady's Seat", "Bear's Cave", "Yercaud Lake"],
    location: "230km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Rejuvenate your senses with a trip to the picturesque Yercaud Hill Station. Known for its coffee plantations, serene lakes, and panoramic views, Yercaud is the perfect destination for a relaxing getaway. This tour includes visits to the major attractions of Yercaud and a chance to unwind in nature.",
    itinerary: [
      { time: "6:30 AM", activity: "Pickup from Bangalore" },
      { time: "10:00 AM", activity: "Arrive at Yercaud" },
      { time: "10:30 AM", activity: "Visit Pagoda Point" },
      { time: "12:00 PM", activity: "Explore Lady's Seat and Bear's Cave" },
      { time: "1:30 PM", activity: "Lunch at a local restaurant" },
      { time: "3:00 PM", activity: "Boating at Yercaud Lake" },
      { time: "5:00 PM", activity: "Return journey to Bangalore" },
      { time: "9:00 PM", activity: "Drop at pickup points" },
    ],
    inclusions: [
      "Non-A/C round-trip transport from Bangalore",
      "Lake boating fees",
      "Lunch",
      "Professional guide",
    ],
    exclusions: [
      "Any kind of insurance",
      "Personal expenses",
      "Additional meals",
      "Travel insurance",
      "Tips for guide",
    ],
    whatToBring: [
      "Comfortable clothing",
      "Water bottle",
      "Camera",
      "Light jacket",
      "Sunscreen",
      "Personal medication",
    ],
  },
  {
    id: 11,
    title: "Bandaje Falls Trek",
    description:
      "A scenic adventure through the Western Ghats, leading to a stunning waterfall hidden amidst lush forests and rolling hills. Perfect for nature lovers and thrill-seekers alike.",
    image:
      "https://images.unsplash.com/photo-1454982523318-4b6396f39d3a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
    price: "₹3,899",
    originalPrice: "₹4,399",
    duration: "2 Days / 1 Night",
    difficulty: "Moderate",
    groupSize: "12-15",
    rating: 4.9,
    reviews: 42,
    slug: "bandaje-falls-trek",
    highlights: [
      "Bandaje Falls Trek",
      "Ballarayana Durga Fort",
      "Samse Tea Estate",
    ],
    location: "275km from Bangalore",
    category: "Two Day Trip",
    fullDescription:
      "Bandaje Falls Trek is a scenic adventure through the Western Ghats, leading to a stunning waterfall hidden amidst lush forests and rolling hills. Perfect for nature lovers and thrill-seekers alike.",
    itinerary: [
      { time: "Day 0", activity: "Depart from Bangalore (overnight journey)" },
      { time: "Day 1", activity: "Trek to Bandaje Falls, visit Ballarayana Durga Fort, Samse Tea Estate" },
      { time: "Day 2", activity: "Return journey to Bangalore" },
    ],
    inclusions: [
      "Non-A/C round-trip transport from Bangalore",
      "2 Breakfasts and 1 dinner (Veg and Non Veg)",
      "Trek to Bandaje Falls",
      "Visit to Ballarayana Durga Fort",
      "Samse Tea Estate experience",
      "Dormitory accommodation (separate for men and women)",
      "Abhi Trip trek coordinator",
      "Basic first aid kit",
    ],
    exclusions: [
      "Any kind of insurance",
      "Personal Expenses (snacks, mineral water, etc)",
      "Anything not included above",
    ],
    whatToBring: [
      "Trekking shoes",
      "Water bottle",
      "Raincoat",
      "Snacks",
      "Personal medication",
    ],
  },
];
