import { Trip } from "./types";

export const trips: Trip[] = [
  {
    id: 1,
    title: "Nandi Hills Sunrise Trek",
    description:
      "Witness the breathtaking sunrise from the historic Nandi Hills, perfect for photography enthusiasts and nature lovers.",
    image:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    price: "₹1,299",
    originalPrice: "₹1,599",
    duration: "1 Day",
    difficulty: "Easy",
    groupSize: "15-25",
    rating: 4.7,
    reviews: 89,
    slug: "nandi-hills-sunrise-trek",
    highlights: ["Sunrise viewpoint", "Historical fort", "Photography spots", "Bird watching"],
    location: "60km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Experience the magic of sunrise from one of Karnataka's most popular hill stations. Nandi Hills offers breathtaking panoramic views, ancient fort ruins, and excellent photography opportunities. This easy trek is perfect for beginners and families looking for a memorable day trip from Bangalore.",
    itinerary: [
      { time: "4:00 AM", activity: "Pickup from Bangalore" },
      { time: "5:30 AM", activity: "Reach Nandi Hills base" },
      { time: "6:00 AM", activity: "Trek to sunrise point" },
      { time: "6:30 AM", activity: "Sunrise viewing and photography" },
      { time: "8:00 AM", activity: "Explore historical fort" },
      { time: "9:30 AM", activity: "Breakfast at local restaurant" },
      { time: "11:00 AM", activity: "Return journey to Bangalore" },
      { time: "1:00 PM", activity: "Drop at pickup points" },
    ],
    inclusions: [
      "Transportation from Bangalore",
      "Professional guide",
      "Entry fees",
      "Breakfast",
      "Photography assistance",
      "First aid kit",
    ],
    exclusions: ["Personal expenses", "Additional meals", "Travel insurance", "Tips for guide"],
    whatToBring: [
      "Comfortable trekking shoes",
      "Water bottle",
      "Camera",
      "Light jacket",
      "Sunscreen",
      "Personal medication",
    ],
  },
  {
    id: 2,
    title: "Coorg Coffee Plantation Experience",
    description:
      "Immerse yourself in the lush greenery of Coorg's coffee plantations and learn about the coffee-making process.",
    image:
      "https://images.unsplash.com/photo-1573674401446-87cae8d4d28e?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹1,499",
    originalPrice: "₹1,799",
    duration: "1 Day",
    difficulty: "Easy",
    groupSize: "10-20",
    rating: 4.8,
    reviews: 120,
    slug: "coorg-trip",
    highlights: ["Coffee plantation visit", "Coffee tasting", "Nature walk", "Scenic viewpoints"],
    location: "250km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Discover the rich flavors and aromas of Coorgi coffee on this delightful day tour. Explore the sprawling coffee plantations, learn about the intricate coffee-making process, and enjoy breathtaking views of the Western Ghats. This tour is a must for coffee enthusiasts and nature lovers alike.",
    itinerary: [
      { time: "6:00 AM", activity: "Pickup from Bangalore" },
      { time: "9:00 AM", activity: "Arrive at Coorg coffee plantation" },
      { time: "9:30 AM", activity: "Guided tour of the plantation" },
      { time: "11:00 AM", activity: "Coffee tasting session" },
      { time: "12:30 PM", activity: "Lunch at a local Coorgi restaurant" },
      { time: "2:00 PM", activity: "Nature walk in the coffee estate" },
      { time: "4:00 PM", activity: "Return journey to Bangalore" },
      { time: "8:00 PM", activity: "Drop at pickup points" },
    ],
    inclusions: [
      "Transportation from Bangalore",
      "Plantation entry fees",
      "Coffee tasting",
      "Lunch",
      "Professional guide",
    ],
    exclusions: ["Personal expenses", "Additional meals", "Travel insurance", "Tips for guide"],
    whatToBring: [
      "Comfortable walking shoes",
      "Water bottle",
      "Camera",
      "Light jacket",
      "Sunscreen",
      "Personal medication",
    ],
  },
  {
    id: 3,
    title: "Chikmagalur Hill Station Retreat",
    description:
      "Explore the royal heritage of Mysore with a visit to the magnificent Mysore Palace and the sacred Chamundi Hill.",
    image:
      "https://images.unsplash.com/photo-1573674401446-87cae8d4d28e?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    price: "₹1,099",
    originalPrice: "₹1,399",
    duration: "1 Day",
    difficulty: "Easy",
    groupSize: "15-30",
    rating: 4.6,
    reviews: 75,
    slug: "chikmagalur-trip",
    highlights: ["Mysore Palace", "Chamundi Hill", "Devaraja Market", "St. Philomena's Church"],
    location: "145km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Step into the regal past of Mysore on this enriching day tour. Marvel at the stunning architecture and opulent interiors of the Mysore Palace, a UNESCO World Heritage Site. Then, visit the sacred Chamundi Hill, home to the famous Chamundeshwari Temple. This tour is perfect for history buffs and spiritual seekers.",
    itinerary: [
      { time: "7:00 AM", activity: "Pickup from Bangalore" },
      { time: "9:30 AM", activity: "Arrive at Mysore Palace" },
      { time: "10:00 AM", activity: "Guided tour of Mysore Palace" },
      { time: "12:00 PM", activity: "Visit Chamundi Hill and temple" },
      { time: "1:30 PM", activity: "Lunch at a local restaurant" },
      { time: "3:00 PM", activity: "Explore Devaraja Market" },
      { time: "4:30 PM", activity: "Visit St. Philomena's Church" },
      { time: "6:00 PM", activity: "Return journey to Bangalore" },
      { time: "9:00 PM", activity: "Drop at pickup points" },
    ],
    inclusions: [
      "Transportation from Bangalore",
      "Palace entry fees",
      "Lunch",
      "Professional guide",
    ],
    exclusions: ["Personal expenses", "Additional meals", "Travel insurance", "Tips for guide"],
    whatToBring: [
      "Comfortable walking shoes",
      "Water bottle",
      "Camera",
      "Light jacket",
      "Sunscreen",
      "Personal medication",
    ],
  },
  {
    id: 4,
    title: "Gokarna Beach Retreat",
    description:
      "Visit the serene beaches and ancient temples of Gokarna, a spiritual and coastal paradise.",
    image:
      "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    price: "₹1,299",
    originalPrice: "₹1,599",
    duration: "1 Day",
    difficulty: "Easy",
    groupSize: "15-30",
    rating: 4.5,
    reviews: 60,
    slug: "gokarna-murudeshwar-trip",
    highlights: ["Kumta Beach", "Mahabaleshwar Temple", "Mirjan Fort", "Om Beach"],
    location: "485km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Experience the spiritual and natural beauty of Gokarna on this delightful day tour. Visit the ancient Mahabaleshwar Temple, relax on the pristine beaches, and explore the historic Mirjan Fort. This tour is perfect for those seeking a peaceful getaway from the hustle and bustle of city life.",
    itinerary: [
      { time: "6:00 AM", activity: "Pickup from Bangalore" },
      { time: "10:30 AM", activity: "Arrive at Mahabaleshwar Temple" },
      { time: "11:30 AM", activity: "Visit Mirjan Fort" },
      { time: "1:00 PM", activity: "Lunch at a local restaurant" },
      { time: "2:30 PM", activity: "Relax at Kumta Beach" },
      { time: "4:00 PM", activity: "Visit Om Beach" },
      { time: "6:00 PM", activity: "Return journey to Bangalore" },
      { time: "10:00 PM", activity: "Drop at pickup points" },
    ],
    inclusions: [
      "Transportation from Bangalore",
      "Temple and fort entry fees",
      "Lunch",
      "Professional guide",
    ],
    exclusions: ["Personal expenses", "Additional meals", "Travel insurance", "Tips for guide"],
    whatToBring: [
      "Comfortable clothing",
      "Water bottle",
      "Camera",
      "Swimwear and towel",
      "Sunscreen",
      "Personal medication",
    ],
  },
  {
    id: 5,
    title: "Kabini Wildlife Sanctuary Safari",
    description:
      "Embark on an exciting safari adventure in the Kabini Wildlife Sanctuary, home to diverse flora and fauna.",
    image:
      "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    price: "₹2,499",
    originalPrice: "₹2,999",
    duration: "1 Day",
    difficulty: "Moderate",
    groupSize: "10-20",
    rating: 4.9,
    reviews: 200,
    slug: "kabini-wildlife-sanctuary-safari",
    highlights: ["Wildlife safari", "Bird watching", "Nature trails", "Kabini River"],
    location: "220km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Experience the thrill of a wildlife safari in the pristine Kabini Wildlife Sanctuary. Home to elephants, tigers, leopards, and a variety of birds, Kabini offers an unforgettable wildlife experience. This tour includes a guided safari, nature walks, and bird watching, making it perfect for wildlife enthusiasts and photographers.",
    itinerary: [
      { time: "5:30 AM", activity: "Pickup from Bangalore" },
      { time: "8:30 AM", activity: "Arrive at Kabini Wildlife Sanctuary" },
      { time: "9:00 AM", activity: "Morning safari in the sanctuary" },
      { time: "12:00 PM", activity: "Lunch at the resort" },
      { time: "2:00 PM", activity: "Afternoon nature walk" },
      { time: "4:00 PM", activity: "Evening safari in the sanctuary" },
      { time: "7:00 PM", activity: "Return journey to Bangalore" },
      { time: "10:00 PM", activity: "Drop at pickup points" },
    ],
    inclusions: [
      "Transportation from Bangalore",
      "Safari permits",
      "Lunch",
      "Professional guide",
    ],
    exclusions: ["Personal expenses", "Additional meals", "Travel insurance", "Tips for guide"],
    whatToBring: [
      "Comfortable clothing",
      "Water bottle",
      "Camera",
      "Binoculars",
      "Sunscreen",
      "Personal medication",
    ],
  },
  {
    id: 6,
    title: "Hampi Historical Tour",
    description:
      "Discover the ancient ruins and rich history of Hampi, a UNESCO World Heritage Site.",
    image:
      "https://images.unsplash.com/photo-1568605114967-8130f3a7a7a4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    price: "₹1,799",
    originalPrice: "₹2,199",
    duration: "1 Day",
    difficulty: "Moderate",
    groupSize: "10-25",
    rating: 4.7,
    reviews: 95,
    slug: "hampi-historical-tour",
    highlights: ["Vijaya Vittala Temple", "Virupaksha Temple", "Hampi Bazaar", "Matanga Hill"],
    location: "340km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Step back in time and explore the fascinating ruins of Hampi, once the capital of the Vijayanagara Empire. This tour takes you to the most iconic landmarks of Hampi, including the stunning Vijaya Vittala Temple and the ancient Virupaksha Temple. Enjoy a guided tour of the historical sites and learn about the rich heritage of this UNESCO World Heritage Site.",
    itinerary: [
      { time: "6:00 AM", activity: "Pickup from Bangalore" },
      { time: "10:00 AM", activity: "Arrive at Hampi" },
      { time: "10:30 AM", activity: "Visit Vijaya Vittala Temple" },
      { time: "12:00 PM", activity: "Explore Virupaksha Temple" },
      { time: "1:30 PM", activity: "Lunch at a local restaurant" },
      { time: "3:00 PM", activity: "Walk through Hampi Bazaar" },
      { time: "4:30 PM", activity: "Sunset view from Matanga Hill" },
      { time: "6:00 PM", activity: "Return journey to Bangalore" },
      { time: "10:00 PM", activity: "Drop at pickup points" },
    ],
    inclusions: [
      "Transportation from Bangalore",
      "Temple entry fees",
      "Lunch",
      "Professional guide",
    ],
    exclusions: ["Personal expenses", "Additional meals", "Travel insurance", "Tips for guide"],
    whatToBring: [
      "Comfortable walking shoes",
      "Water bottle",
      "Camera",
      "Light jacket",
      "Sunscreen",
      "Personal medication",
    ],
  },
  {
    id: 7,
    title: "Chikmagalur Coffee and Spice Plantation Tour",
    description:
      "Explore the aromatic coffee and spice plantations of Chikmagalur and enjoy a day amidst nature.",
    image:
      "https://images.unsplash.com/photo-1521747116042-5a810fda9664?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    price: "₹1,699",
    originalPrice: "₹2,099",
    duration: "1 Day",
    difficulty: "Easy",
    groupSize: "10-20",
    rating: 4.8,
    reviews: 110,
    slug: "chikmagalur-coffee-spice-plantation-tour",
    highlights: ["Coffee plantation tour", "Spice garden visit", "Nature walk", "Scenic views"],
    location: "280km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Delight your senses with a tour of Chikmagalur's famous coffee and spice plantations. Learn about the cultivation and processing of coffee and spices, and enjoy the fresh mountain air and stunning views of the Western Ghats. This tour is a perfect escape for nature and coffee lovers.",
    itinerary: [
      { time: "6:30 AM", activity: "Pickup from Bangalore" },
      { time: "10:00 AM", activity: "Arrive at Chikmagalur plantation" },
      { time: "10:30 AM", activity: "Guided tour of coffee plantation" },
      { time: "12:00 PM", activity: "Visit spice garden" },
      { time: "1:30 PM", activity: "Lunch at a plantation homestay" },
      { time: "3:00 PM", activity: "Nature walk in the plantation" },
      { time: "5:00 PM", activity: "Return journey to Bangalore" },
      { time: "9:00 PM", activity: "Drop at pickup points" },
    ],
    inclusions: [
      "Transportation from Bangalore",
      "Plantation entry fees",
      "Lunch",
      "Professional guide",
    ],
    exclusions: ["Personal expenses", "Additional meals", "Travel insurance", "Tips for guide"],
    whatToBring: [
      "Comfortable walking shoes",
      "Water bottle",
      "Camera",
      "Light jacket",
      "Sunscreen",
      "Personal medication",
    ],
  },
  {
    id: 8,
    title: "Sakleshpur Homestay and Trek",
    description:
      "Experience the beauty of Sakleshpur with a homestay and trek in the scenic Western Ghats.",
    image:
      "https://images.unsplash.com/photo-1514516874920-4f3f3c8e4f3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    price: "₹2,199",
    originalPrice: "₹2,699",
    duration: "1 Day",
    difficulty: "Moderate",
    groupSize: "10-15",
    rating: 4.7,
    reviews: 85,
    slug: "sakleshpur-homestay-trek",
    highlights: ["Homestay experience", "Trekking", "Coffee plantation visit", "Nature exploration"],
    location: "220km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Enjoy a perfect blend of adventure and relaxation with a homestay and trek in Sakleshpur. Explore the lush green landscapes, coffee plantations, and scenic viewpoints of the Western Ghats. This tour offers a unique opportunity to experience the local culture and hospitality of Karnataka.",
    itinerary: [
      { time: "6:00 AM", activity: "Pickup from Bangalore" },
      { time: "9:00 AM", activity: "Arrive at Sakleshpur homestay" },
      { time: "9:30 AM", activity: "Breakfast and orientation" },
      { time: "10:30 AM", activity: "Trek to Ettina Bhuja" },
      { time: "1:00 PM", activity: "Lunch at the homestay" },
      { time: "2:00 PM", activity: "Visit coffee plantation" },
      { time: "4:00 PM", activity: "Nature walk and bird watching" },
      { time: "6:00 PM", activity: "Campfire and dinner" },
      { time: "8:00 PM", activity: "Return journey to Bangalore" },
      { time: "11:00 PM", activity: "Drop at pickup points" },
    ],
    inclusions: [
      "Transportation from Bangalore",
      "Homestay accommodation",
      "All meals",
      "Trekking and plantation fees",
      "Professional guide",
    ],
    exclusions: ["Personal expenses", "Travel insurance", "Tips for guide"],
    whatToBring: [
      "Comfortable trekking shoes",
      "Water bottle",
      "Camera",
      "Light jacket",
      "Sunscreen",
      "Personal medication",
    ],
  },
  {
    id: 9,
    title: "Kabini River Rafting and Wildlife Tour",
    description:
      "Experience the thrill of river rafting and the beauty of wildlife in the Kabini region.",
    image:
      "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    price: "₹2,999",
    originalPrice: "₹3,499",
    duration: "1 Day",
    difficulty: "Moderate",
    groupSize: "10-15",
    rating: 4.9,
    reviews: 150,
    slug: "kabini-river-rafting-wildlife-tour",
    highlights: ["River rafting", "Wildlife safari", "Bird watching", "Nature trails"],
    location: "220km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Get ready for an adrenaline-pumping adventure in the Kabini region. This tour combines the excitement of river rafting with the tranquility of a wildlife safari. Explore the rich biodiversity of the Kabini Wildlife Sanctuary and enjoy a thrilling rafting experience on the Kabini River.",
    itinerary: [
      { time: "6:00 AM", activity: "Pickup from Bangalore" },
      { time: "9:00 AM", activity: "Arrive at Kabini River base" },
      { time: "9:30 AM", activity: "Safety briefing and rafting gear allocation" },
      { time: "10:00 AM", activity: "River rafting on Kabini River" },
      { time: "1:00 PM", activity: "Lunch at a riverside restaurant" },
      { time: "2:30 PM", activity: "Wildlife safari in Kabini Wildlife Sanctuary" },
      { time: "5:30 PM", activity: "Return journey to Bangalore" },
      { time: "8:30 PM", activity: "Drop at pickup points" },
    ],
    inclusions: [
      "Transportation from Bangalore",
      "Rafting and safari permits",
      "Lunch",
      "Professional guide",
    ],
    exclusions: ["Personal expenses", "Additional meals", "Travel insurance", "Tips for guide"],
    whatToBring: [
      "Quick-dry clothing",
      "Water bottle",
      "Camera",
      "Swimwear and towel",
      "Sunscreen",
      "Personal medication",
    ],
  },
  {
    id: 10,
    title: "Yercaud Hill Station Tour",
    description:
      "Escape to the serene Yercaud Hill Station and enjoy the cool climate and beautiful landscapes.",
    image:
      "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
    price: "₹1,899",
    originalPrice: "₹2,299",
    duration: "1 Day",
    difficulty: "Easy",
    groupSize: "15-25",
    rating: 4.6,
    reviews: 70,
    slug: "yercaud-hill-station-tour",
    highlights: ["Pagoda Point", "Lady's Seat", "Bear's Cave", "Yercaud Lake"],
    location: "230km from Bangalore",
    category: "One Day Trip",
    fullDescription:
      "Rejuvenate your senses with a trip to the picturesque Yercaud Hill Station. Known for its coffee plantations, serene lakes, and panoramic views, Yercaud is the perfect destination for a relaxing getaway. This tour includes visits to the major attractions of Yercaud and a chance to unwind in nature.",
    itinerary: [
      { time: "6:30 AM", activity: "Pickup from Bangalore" },
      { time: "10:00 AM", activity: "Arrive at Yercaud" },
      { time: "10:30 AM", activity: "Visit Pagoda Point" },
      { time: "12:00 PM", activity: "Explore Lady's Seat and Bear's Cave" },
      { time: "1:30 PM", activity: "Lunch at a local restaurant" },
      { time: "3:00 PM", activity: "Boating at Yercaud Lake" },
      { time: "5:00 PM", activity: "Return journey to Bangalore" },
      { time: "9:00 PM", activity: "Drop at pickup points" },
    ],
    inclusions: [
      "Transportation from Bangalore",
      "Lake boating fees",
      "Lunch",
      "Professional guide",
    ],
    exclusions: ["Personal expenses", "Additional meals", "Travel insurance", "Tips for guide"],
    whatToBring: [
      "Comfortable clothing",
      "Water bottle",
      "Camera",
      "Light jacket",
      "Sunscreen",
      "Personal medication",
    ],
  },
];
